tweets = [("is so sad for my APL friend.............",'negative'),
          ("I missed the New Moon trailer...",'negative'),
          (".. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2 just get a crown put on (30mins)...",'negative'),
          ("i think mi bf is cheating on me!!! T_T",'negative'),
          ("or i just worry too much?",'negative'),
          ("Sunny Again Work Tomorrow :-| TV Tonight",'negative'),
          ("this weekend has sucked so far",'negative'),
          ("b isnt showing in australia any more!",'negative'),
          ("This is the way i feel right now...",'negative'),
          ("awhhe man.... I'm completely useless rt now. Funny, all I can do is twitter.",'negative'),
          ("HUGE roll of thunder just now...SO scary!!!!",'negative'),
          ("I just cut my beard off. It's only been growing for well over a year. I'm gonna start it over.",'negative'),
          ("Very sad about Iran.",'negative'),
          ("Sad level is 3. I was writing a massive blog tweet on Myspace and my comp shut down. Now it's all lost lays in fetal position",'negative'),
          ("Headed to Hospitol : Had to pull out of the Golf Tourny in 3rd place!!!!!!!!!!! I Think I Re-Ripped something !!! Yeah THAT !!",'negative'),
          ("): whats wrong with him?? Please tell me........ :-/",'negative'),
          ("can't be bothered. i wish i could spend the rest of my life just sat here and going to gigs. seriously.",'negative'),
          ("Feeeling like shit right now. I really want to sleep, but nooo I have 3 hours of dancing and an art assignment to finish.",'negative'),
          ("I didn't realize it was THAT deep. Geez give a girl a warning atleast!",'negative'),
          ("I hate it when any athlete appears to tear an ACL on live television.",'negative'),
          ("i miss you guys too i think i'm wearing skinny jeans a cute sweater and heels not really sure what are you doing today",'negative'),
          ("My horsie is moving on Saturday morning.",'negative'),
          ("No Sat off...Need to work 6 days a week",'negative'),
          ("Really Dont Like Doing my Room Its So Boring Sick Of Doing My Wardrobe Out Cant Waiit Till I Have My Walk In One Yay",'negative'),
          ("SOX! Floyd was great, but relievers need a scolding!",'negative'),
          ("what type of a spaz downloads a virus? my brother that's who :\ MSN is now fucked forever :'(",'negative'),
          ("Fightiin Wiit The Babes...",'negative'),
          ("enough said",'negative'),
          ("it really makes me sad when i look at Muslims reality now",'negative'),
          ("and the entertainment is over, someone complained properly.. experimental you say? he should experiment with a melody",'negative'),
          ("another year of Lakers .. That's neither magic nor fun ...",'negative'),
          ("baddest day eveer.",'negative'),
          ("David must be hospitalized for five days end of July (palatine tonsils). I will probably never see Katie in concert. ",'negative'),
          ("friends are leaving me 'cause of this stupid love",'negative'),
          ("hate u ...  leysh tears ... =((((((( ..",'negative'),
          ("I miss Earl",'negative'),
          ("I miss New Jersey",'negative'),
          ("I missed the first hour of SYTYCD last night, and I can't find it online!",'negative'),
          ("I never thought I'd become second choice...",'negative'),
          ("I think I may be too friendly...lol... o well...",'negative'),
          ("I think Manuel (my Basil plant) only has days to live",'negative'),
          ("I wanna be at home...I wonder wht they are doing?",'negative'),
          ("i wanna make my own pizza",'negative'),
          ("I wanted to sleep in this morning but a mean kid through a popsicle stick at me head. I wish I could fly away like those squirrels",'negative'),
          ("i was too slow to get $1 Up tix",'negative'),
          ("I wish I could go to T4 On The Beach :'( Would be great to see",'negative'),
          ("i would be so much happier if the walls of my bedroom were painted white",'negative'),
          ("idk wat 2 do who can i trust me im sorry 4 all da pain i have caused nebody ima take dis time out 2 straighten myself out i luv yall",'negative'),
          ("I'm finding the intercept slope..and banging my head against the wall..Math brain heads come save me",'negative'),
          ("im sick  'cough cough'",'negative'),
          ("in cab headed to the airport!  going home....",'negative'),
          ("jonas day is almost over...",'negative'),
          ("Jus Got Hom Fr. TDa Funeral... I'm So Sad! I Cried So Much Times! Much Love Grandpa! I Never Got To Say My Last Goodbye to Him.",'negative'),
          ("ongest night ever.. ugh!",'negative'),
          ("mi momacita won't let me go to my bf's bball game!!! grrr!!!",'negative'),
          ("My new car was stolen....by my mother who wanted to go pose at church.",'negative'),
          ("no hang out with the girls 2day. 2moro, hope so......",'negative'),
          ("no movie times for sunday!  Rats will have to plan tomorrow. I guess this means I have to work on those two  presentations I am doing!",'negative'),
          ("not a cool night.",'negative'),
          ("probably guna get off soon since no one is talkin no more",'negative'),
          ("really wanted Safina to pull out a win to lose like that...",'negative'),
          ("RIP, David Eddings.",'negative'),
          ("sorry The Ex Husband has overdosed on his daily dose of haterade",'negative'),
          ("Thanks for your definition of throwbie!  Editors reviewed your entry and have decided to not publish it.",'negative'),
          ("told not to drink w/my Rx so just gave all the b.b. porter obs. stout that I brought home from OR to my neighbors.  v, v, sad.",'negative'),
          ("waahhh now I'm getting sad....miss hub :-'(",'negative'),
          ("we were standing out in the pouring rain.. We were sitting on top of the world..  --   summer sucks ",'negative'),
          ("Went to get dog from vets, theyve stitched her ear, charged us for it but she still bleeds like a waterfall everytime she moves. D: WHY!",'negative'),
          ("where is my picture i feel naked ",'negative'),
          ("Why aren't there any trains going to manchester on a sunday?!!  Now I can't go to the concert.",'negative'),
          ("Why must people be so picky. I mean 6 hours work and no dice!? what's up with that!",'negative'),
          ("Why Twitter will soon become obsolete?",'negative'),
          ("turn off words this shit sucks",'negative'),
          ("asylm J2 panel is over. Guess it's back to normal life.",'negative'),
          ("squarespace brighten my bad day! i never win anything...",'negative'),
          ("Susan Boyle didnt win! mh well, diversity was very good though! CONGRATZ!!",'negative'),
          ("Vandals paint swastikas on home of author of gay, lesbian church story : Naples Daily News",'negative'),
          ("An unknown error occured (-4). uh oh. iPhone OS 3 fail so far ",'negative'),
          ("Try to turn on my tv to get you out of my head. I've got this feeling inside that I just won't admit... (that is literally how I feel)",'negative'),
          ("well, the truth is I miss you so - Coldplay",'negative'),
          ("tears :'-( Today is the last day with my kids...They go on summer break at their Dads tomorrow. sighs",'negative'),
          ("Beautifully Lost",'negative'),
          ("cries I'm going to miss Harry Potter when it comes out.  I'm leaving to Vietnam on July 11th.  I'm going to cry!!",'negative'),
          ("going back to bed, because I'm lookin' around and don't see a reason to be awake atm. Be up in a little.",'negative'),
          ("watching tv , bed, shopping w. mom, out w. trent hopefully, i need my best friend",'negative'),
          ("had weird encounters with so many homeless/creeps on the walk home tonight all by myself   awesome... really...",'negative'),
          ("Rained out truck race",'negative'),
          ("Feeling pain and happiness at the same time. How confusing!",'negative'),
          ("....in a shirt and panties. celulite",'negative'),
          ("had to turn back to North due to body on line. So missing Design Council Design 4 Tech Transfer event",'negative'),
          ("y everything is so hard? :/",'negative'),
          (":[ I don't want to move!!!",'negative'),
          ("the train crash in DC",'negative'),
          ("I went to work once last year with no pants. Ironically, that was my last day of work at that job. FML",'negative'),
          ("fringe is only 10 weeks away?! I need monies",'negative'),
          ("why didnt you come to school?? have you done the short stack thing by yourself, or do you still need me?",'negative'),
          ("ow who wud make this beautiful plc cry?",'negative'),
          ("it is now the outer fat kid.",'negative'),
          ("Why is your YouTube account suspended? lol Single Ladies dance? I NEED TO WATCH IT AGAIN!",'negative'),
          ("I know.. SOLD OUT though.",'negative'),
          ("should get on aim and talk to me. i miss her.",'negative'),
          ("I'm immune to dentists' drills etc now, it just doesn't bother me at all. Having gum lift surgery next week tho eek",'negative'),
          ("where r u tonite im still awake!",'negative'),
          ("hates Bebot App",'negative'),
          ("What are u referring to?",'negative'),
          ("I miss her so much already...",'negative'),
          ("FUCK YOU!",'negative'),
          ("my head feels like a bowling ball",'negative'),
          ("my heart hurts badly...",'negative'),
          ("FS keeps crashing when I try to load Bungie plane.",'negative'),
          ("My current headset is on its deathbed now!  My dad gave it to me just 3 weeks back!",'negative'),
          ("My mood is currently BLAH . Sitting in a parking lot",'negative'),
          ("that is all.",'negative'),
          ("everyone went home. and not everyone was even here!",'negative'),
          ("fed up....",'negative'),
          ("fuck, fuck, fuuuuck!",'negative'),
          ("Not feeling it today And to make matters worst its super nasty and rainy outside, YUCK!",'negative'),
          ("Friends like these ... no thanks, I'm not fake!",'negative'),
          ("i want to find a way to put my photos on phone here i have Bluetooth in both phone and computer but it doesn't work",'negative'),
          ("J, you are right... it hurts.",'negative'),
          ("let's have a moment of silence for our childhood homes... sadly, it can't be replaced and we can never go back",'negative'),
          ("No man is worth your tears, and the one that is won't make you cry!",'negative'),
          ("rain rain go away!",'negative'),
          ("storms are scary!",'negative'),
          ("Tell those girls your clocking out lol",'negative'),
          ("the batt to my internet connection died.  Guess its back to the mobile!",'negative'),
          ("no apple iphone card for us  maybe tomorrow! I guess it helps if you tweet it huh?  We forgot ",'negative'),
          ("exhausted",'negative'),
          ("i want some ben jerrys cake batter please ugh",'negative'),
          ("wish ella was on or somebody",'negative'),
          ("i think i'm going to go 3 a long drive then when i get to the pacific ocean open my car door and throw my pc in the ocean",'negative'),
          ("what the hell BBC?",'negative'),
          ("I dont like this weekend.. Huhuhu ( (",'negative'),
          ("lonely night",'negative'),
          ("blue does not work",'negative'),
          ("geez I'm feeling their pain",'negative'),
          ("i miss my summertime daley.",'negative'),
          ("on the computer ... . . . . . . ill    lol,       no fuckin goin to portugal ",'negative'),
          ("UGHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",'negative'),
          ("Awwwwwh  i wanted Aiden Davis 2 WIN i him so bummed he didnt ",'negative'),
          ("eh must leave New Mexico and soon!",'negative'),
          ("fail maths  i knew it i was just too slow ",'negative'),
          ("fuck sake. Why can things never work out for me?",'negative'),
          ("going in town with cousinnn, netball match was cancelledd",'negative'),
          ("i don't even know.",'negative'),
          ("I just lost a member of my family",'negative'),
          ("I'm SICK of bedtime battles",'negative'),
          ("i'm so cold this morning......       i have chills all over..... ",'negative'),
          ("No no no. Tonight goes on the books as the worst SYTYCD results show.",'negative'),
          ("no shopping",'negative'),
          ("Poor lil mousey, just out enjoying the sunny day. I don't think I'd feel so bad if it was a big gnarly rat though. Dbl standard? Yep.",'negative'),
          ("that's an EPIC sad face.",'negative'),
          ("This magazine story just broke my heart at the dentist's office today",'negative'),
          ("wanna go meet wifey but can't....  this sux   :'(",'negative'),
          ("Wondering why I feel like I do...I'll feel better though...Its all good! I'll be happy inspite of...Tweet ya lata",'negative'),
          ("no one realizes how deep this goes.",'negative'),
          ("Bodies from Air France crash have been found",'negative'),
          ("that is the story of my life, a whole bunch of frownies!",'negative'),
          ("I HAVE NOOOOOOOOOO FRIENDS ON TWITTER IT MAKES ME SAD WILL SOMEONE FOLLOW ME",'negative'),
          ("i just want to hear from you. i guess that's asking too much..",'negative'),
          ("alergic... nose itchy and eyes burning... Hope It's getting better soon....",'negative'),
          ("Another expensive weekend trip to the vet.",'negative'),
          ("are there any parties tonight!? im hella bored at home, and its seems like everyone is busy!! LAMMMMEEE",'negative'),
          ("but chilli prawns will make the pain better...",'negative'),
          ("daughter's beloved diabetic dwarf hamster died in her hands this morning...all creatures are worthy of love.",'negative'),
          ("DD has pinkeye...not fun",'negative'),
          ("Farrah Fawcett Dies of Cancer at 62",'negative'),
          ("feeling hopeless and useless",'negative'),
          ("forgot my lunch at home",'negative'),
          ("General Motors sold hummer :S :S",'negative'),
          ("goodnight..",'negative'),
          ("gooood night!!   must prepare for tomorrows meeting now",'negative'),
          ("Great! Im bored at the moment and just have no idea on what to do!  Missing Boyfie too! Damn",'negative'),
          ("I am actually crying now because of sore throat.",'negative'),
          ("I feel irresponsible and sort of horrible. Marshmallows, unless otherwise stated, have gelatin. fuck...",'negative'),
          ("i miss my brother.. i worry about him",'negative'),
          ("i need to think of something else, first",'negative'),
          ("i wanted julian to win!",'negative'),
          ("jus got some bad news",'negative'),
          ("just mean",'negative'),
          ("Love, save the empty",'negative'),
          ("my camera broke !",'negative'),
          ("my parents left",'negative'),
          ("no ass beatings, checked out Playhouse in Baltimore this weekend as well.  Feeling quite rested and a bit out of sorts.",'negative'),
          ("nothing....",'negative'),
          ("server problems - motivating me to change hosting providers though...",'negative'),
          ("shakes head",'negative'),
          ("Shock loss to Sparks...bummer, had a great game but shock too many injuries to start the season...rematch Monday!",'negative'),
          ("some asshole got a hold of my email and signed me up for all this spam mail.  ughhhh...it's non stop.  anyone have a spam blocker?",'negative'),
          ("someone just said ast least your pretty  . thanks but but being pretty gets you nowhere you have to much integrity .",'negative'),
          ("myspace people  can get really angry if I don't answer them right away... JA!",'negative'),
          ("never get any photo comments on myspace and more",'negative'),
          ("no tickets in germany for the miley cyrus tour.. ",'negative'),
          ("photo shoot rained out...  oh well, back to post!",'negative'),
          ("RIP Charles J ...the world is with one less fine fellow",'negative'),
          ("RSL was at the Paley talk?! Now I'm even more depressed I couldn't get a ticket. Oh wells.",'negative'),
          ("so bored",'negative'),
          ("so much for a good weekend",'negative'),
          ("The hotel doesn't know where it is either... that was my favorite! How poopie is that.",'negative'),
          ("This year, 5 million children died from hunger-related causes.",'negative'),
          ("To all the mothers whose day may not be so happy.",'negative'),
          ("Today is not a good day. But I guess laying around the house in your undies isn't so bad.",'negative'),
          ("went to maggie's bday party, came home without my phone... I feel lost, and reaally confused (but thats just the booze talking)",'negative'),
          ("my grandma just told me she thinks I'm stupid. Well, hey thanks, G.",'negative'),
          ("why are you doing this to me? This necklace is $150 rather than the usual $50-60 I want it",'negative'),
          ("no signal detected here at the gardens",'negative'),
          ("It's raining again",'negative'),
          ("you have to do it all alone",'negative'),
          ("Apparently the 'new' 3.0 is the same build as the GM, meaning I'll likely have the same [minute] issues I was having with the GM.",'negative'),
          ("Archie's annoying me this morning, says I hogged the bed all night and won't get up for his shower, him and his little black kettle self",'negative'),
          ("are you ok?",'negative'),
          ("Argh, the speakers on my Macbook are screwing up, and slowly dying.",'negative'),
          ("at Chris Brown . . . I honestly dont feel bad for Rihanna ; anyways . . . Out and such . . .",'negative'),
          ("at work ! Fuck !",'negative'),
          ("at work and got loads to do b4 I leave today. Toodles lufflies xxx",'negative'),
          ("attempting to get other people on twitter(other than cate)  to talk to me but it is failing",'negative'),
          ("AWW I GOTA DO HOMEWORK",'negative'),
          ("aww someone borrowed it without telling me.",'negative'),
          ("Awww derek is at work back to making kandie with the little ones  :o",'negative'),
          ("B- in genetics so that's a 2.75 towards my GPA. What really sucks is that I got a 79.75% in the class and an 80% is a B.",'negative'),
          ("baby died last night.",'negative'),
          ("baby girl's so upset.....i'm not where i need to be with my sewing... and it's almost 10pm and i'm finally eating a little dinner..sigh..",'negative'),
          ("back from cali , missing it",'negative'),
          ("back pain",'negative'),
          ("bad day 2day. Broken glasses  rainy weather  uof",'negative'),
          ("bad night for the pens",'negative'),
          ("bad timing- a new mommy just called for newborn pictures and I can't fit the baby into my schedule no matter how hard I try",'negative'),
          ("bank account is negative $118...",'negative'),
          ("bcd's closed! i guess nodaji it is.",'negative'),
          ("bed ; I gotta get up early  , only 5 more days of this bullshit  . SUMMER!!!",'negative'),
          ("bed is gay ... oh well Goodnight people",'negative'),
          ("being afraid of food is an eating disorder right?",'negative'),
          ("being told i'm beautiful doesnt make my tummy better",'negative'),
          ("The iPhone will be out of commission for a while.",'negative'),
          ("Things are not good in my head. I may not be around a lot this weekend.",'negative'),
          ("twitter wont let me send replies today - boo hoo",'negative'),
          ("ughhh..",'negative'),
          ("water works are gonna start",'negative'),
          ("Well i wrote a missive post about last night and all the things that happened, it got deleted tho",'negative'),
          ("well, I guess I knew it was going to break sometime...",'negative'),
          ("why is it raining?",'negative'),
          ("why me?",'negative'),
          ("you were asleep while i gathered my things in the dark. the burns on my fingers were all that was left of the spark",'negative'),
          ("BBC NEWS | UK maps climate change forecasts - The picture it paints is an alarming one",'negative'),
          ("I'm giving up on you. I don't care how you mess up your life now.",'negative'),
          ("angry mixed motions! but soo frustrated x(",'negative'),
          ("cries I'm so depressed, thanks to you my angel! I'm gonna find someone someday who might actually treat me well",'negative'),
          ("On my way to the doctors with my Duo, my ass hasn't even had breakfast yet  lol",'negative'),
          ("sob must be in bed!!",'negative'),
          ("wishes she was at summer jam",'negative'),
          ("school! GrRr im not in the mood to take my make up back off then put it on again when the teachers leave!",'negative'),
          ("Sunday is over.",'negative'),
          ("why the jonas are bad with us !! come to paraguay",'negative'),
          ("UghH... Anybody wanna come to my house and cook? My mom is leavin for work and aint cook me shit !... Can't trust dem hoes!!!",'negative'),
          ("i don't know what to do..",'negative'),
          ("i think i lost my spanish book!! :-X",'negative'),
          ("Life can be so complicated. I know God has a plan .... I just have to trust in him.",'negative'),
          ("Oh well, at least Suzumiya Haruhi no Yuuutsu is on air.",'negative'),
          ("not really a good night guys ! buu huu",'negative'),
          ("I did not get cast in but I will keep looking for some dance opportunities.  I need some exercise.",'negative'),
          ("the ground around me is wet... i looked up to see if any drops fall on my face...it was drizzle all around but I am missing my drops",'negative'),
          ("i forgot to bring my new sharpie pens to school today..booo!",'negative'),
          ("omg...my celly is off...this hasn't happened to me in years...WTF!!! gota get my bill paid",'negative'),
          (":'( this is so horrible",'negative'),
          (":'( where is that one person that can make me smile ",'negative'),
          (":S this tweetdeck is killing me hate it",'negative'),
          ("saw that earlier, can't even comprehend what that couple were feeling. Really tragic",'negative'),
          ("I hope it's not actually on here birthday that she's getting shots.",'negative'),
          ("signature has 100% rubbed off my mondayeyes bracelet. At least I have plenty of autographs from him, but still. Sad day.",'negative'),
          ("Alan ruins my lifeeee.",'negative'),
          ("I wanted to buy the sims 3 . But it sold out . Wtf . Haha..",'negative'),
          ("yep,i have things my way all the time. i am selfish. everything revolves around me. yep. im a bitch. great for me (Y) =|",'negative'),
          ("I don't wanna get rid of twitter  You guys are too cool...",'negative'),
          ("i try... i try so hard... and i seem to get no credit for it.... wats the prob?",'negative'),
          ("wide awake, but dont actually wanna go to school :S  xxx",'negative'),
          ("now only have one roommate....",'negative'),
          ("Im givin myself 5 minutes to turn that frown upside down",'negative'),
          ("i cant even say a word right now",'negative'),
          ("why am i so sad??...becuz of u or becuz of the exam??.....i think..becuz of u...",'negative'),
          ("frustrated",'negative'),
          ("and i feel a shallow breath that squeezes past the fifty pounds of stone laid in my chest.",'negative'),
          ("just found out that a friend from my childhood has passed away... May he Rest In Peace.",'negative'),
          ("still in the office...",'negative'),
          ("sniffles... since I dont get to leave this fucking house...AW GREAT the power's gone. and its getting dark.. Puurfect!",'negative'),
          ("I feel so ... ... Left out",'negative'),
          ("sigh we didnt win the contest . stupid popularity contest. i had so many votes for her also.  im realy sad. i had such a good feeling",'negative'),
          (";( noooo! why? things are so complicated if I spelt that wrong idc",'negative'),
          ("youtube being suspended",'negative'),
          ("court for a traffic ticket..I should be sleeping..aahh.",'negative'),
          ("i have no car to come to you either.",'negative'),
          ("sold out of frozen bananas today!",'negative'),
          ("has disappeared again ",'negative'),
          ("oi tell your daughter to lower her ticket prices we cant afford it in london  my sister cried.",'negative'),
          ("unfortunately I'm coming from NJ the boonies...I gotta drive to the path",'negative'),
          ("All gigs this weekend have been cancelled, so it may be temporary or shut for good. Still trying to find out. BOO.",'negative'),
          ("is mad at me.",'negative'),
          ("I can't get excited about Conan.",'negative'),
          ("stopped talking to me.",'negative'),
          ("has court on the 24th...",'negative'),
          ("When you meet tonight, please tell him my story. How Laker Fans made me miss his show!",'negative'),
          ("I get too paranoid over things",'negative'),
          ("@Geokypan She wouldn't care if I was sleeping or not. She'd just maintain eye contact as she drew all over everything. Shes a monster.",'negative'),
          ("ok it's fine to leave me on seen but when I do it you get so pissed at me",'negative'),
          ("@McSavageEye If it's any consolation I'd have rescued you from the tree, and bought you a ginbucca to ease the pain.",'negative'),
          ("Dads just picked up two random people from the bus stop cause they've missed it and it's an hourly service #strangerdanger",'negative'),
          ("I seriously hate you, go call your ex back since you obviously miss her",'negative'),
          ("@COYBIG1967 I know one thing the way things are going they be no more 6million pound players.... Like Sutton Hartson etc..",'negative'),
          ("So I treated my son(7)to the unedited version of #templeofdoom hand reaches into chest evil dead style scarred him for life @empiremagazine",'negative'),
          ("@ZofiaSvarna I'm stuck on my analyses, I'm struggling so bad :/",'negative'),
          ("Alpha centauri has arrived. We're all dead.",'negative'),
          ("My wife has gone to Australia for two weeks. Thought it would be a good chance to write, but I'm just lonely. #extrovertproblems",'negative'),
          ("I feel like one of the apes in 2001.",'negative'),
          ("Make my day punk !",'negative'),
          ("@taraandrew2 updated pictures dunno but need to sort out taking full body selfies but your correct about that smile hell I look depressed",'negative'),
          ("I was totally pissed off when the fishsticks beat us....there's nothing better than your team winning..... nothing ! #NYR #LGR",'negative'),
          ("The last time Ronan Finn scored a goal and lost he - like Ciaran Kilduff and David McMillan - was playing for UCD",'negative'),
          ("Someone just put me out of my misery",'negative'),
          ("@roflcopterftw always frowned upon.. unless ur in a hurry",'negative'),
          ("Okay now I'm seeing a girl in a wedding dress carrying around a blow up doll.",'negative'),
          ("@marshmallowylu set the kitchen on fire as a joke lol",'negative'),
          ("@issassin how ayew gets a lower rating than richards is beyond me",'negative'),
          ("@twitter what's going on with the crazy notifications every few minutes, when I tap on the app there's nothing",'negative'),
          ("@WritersofColour Multiculturalism = Destroying Diversity",'negative'),
          ("Nationalism = Preserving Diversity",'negative'),
          ("Just a shame the board were BASTARDS",'negative'),
          ("My brother is so OCD and he's demanding that I empty the bins. Not gonna happen bitch",'negative'),
          ("So bored",'negative'),
          ("Looks like the weather has consumed #Aberdeen @ Balgownie Playing Fields ",'negative'),
          ("@markojemo yea same here lol ur lucky I weren't caught up in that pile up",'negative'),
          ("@Davemoug to say I'm jealous is an understatement",'negative'),
          ("Just got told to go burn my bra jeh know wha hun maybe I fuckin will",'negative'),
          ("@DaveTodayFM @TXFMDublin cool. You know your show isn't even listed don't ya?",'negative'),
          ("I've seemingly been blocked by Frank Monkey for no apparent reason whatsoever #blocked #nojustice",'negative'),
          ("@piersmorgan @JohnBennettBBC pathethic.. no pic today then.",'negative'),
          ("@piersmorgan @JohnBennettBBC you are not manager so shut it",'negative'),
          ("@L0RD_H @Victoria1867 @AwayDaySleepers I can't even go anywhere as I'm trapped.",'negative'),
          ("101 things I should be doing, doing 0",'negative'),
          ("why did I leave revision til the last minute lol a7aaaaa",'negative'),
          ("@Conjob123 @leeoxS6 u wouldn't be complaining if I told u he birdied it",'negative'),
          ("@OGrianain22 This trash may interest you",'negative'),
          ("i flurt to much and drive boys away",'negative'),
          ("@Nadya130993 its my fault",'negative'),
          ("Still not over having to work the 2 days @jamessmurray was in Dublin, my inner fan girl is broken",'negative'),
          ("Im my dads lack of love for me",'negative'),
          ("@DUPleader what about dealing with the gangsters and criminals, time to deal with the elephant in the room.",'negative'),
          ("@viewfinder_m6 My V700 &amp; iMac (El Capitan) does exactly the same - annoying!",'negative'),
          ("Not the start Lowry was hoping for #Masters2016",'negative'),
          ("@sanamshazad na bun that its disgusting, the only way I would EVER eat it is if its got so much breadcumbs and seasoning that I wouldnt kno",'negative'),
          ("@sanamshazad that its liver. fuck that. ewww",'negative'),
          ("Services or as my son calls them Domestic Police :( #autism",'negative'),
          ("Dunno how people can stand on a stage in front of thousands of people, I can barely stand in front of the class",'negative'),
          ("@Grantomac the hidden side of relegation that's not talked about much unfortunately",'negative'),
          ("I know TV is meant to reassure the masses re their stupidity: BUT IS THERE ANYONE WHO DOESN'T SOUND LIKE AN ESSEX HAIRDRESSER PRESENTING??",'negative'),
          ("The drag...",'negative'),
          ("How can anyone get excited about #BGT?  If someone walks on dragging even a three-legged dog behind them they are guaranteed to win it.",'negative'),
          ("Her ma is a fucking ride #BGT",'negative'),
          ("@imgooty no come and fight Me",'negative'),
          ("You're a bit touchy for someone who isn't member of @sdlplive.@columeastwood must be some pup!",'negative'),
          ("Balotelli getting whistled by the Milan fans already 8 minutes in what a fraud of a player he is.",'negative'),
          ("A headteacher who abused my son in primary school is still working as a headteacher. He delivered a school assembly on him #autism #abuse",'negative'),
          ("@terryaanderson we were robbed",'negative'),
          ("@weslimtogether @barrabest That's a dodgy looking forecast!",'negative'),
          ("love when I ask someone to do just 1 thing &amp; they always forget....thanks!",'negative'),
          ("@UrbanCityCowboy @W_Autism_Comm Hopeless, I dont trust them as far as I can throw them and I have never met a nice one! Sadly do they exist?",'negative'),
          ("I have to say I don't entirely agree with this, there are benefits to SMedia usage,even more than 1hr a day!#smedia",'negative'),
          ("Well fuck",'negative'),
          ("when you do your entire eye makeup then realise you forgot to use a primer",'negative'),
          ("@CharlieJones what the actual fuck",'negative'),
          ("Hormones are terrible things!! I need a tissue and for the cat to wake up and get off the fecking TV remote so I can change the channel! Lol",'negative'),
          ("It's 2016 and people still make Anne Frank jokes I would say she's freaked out",'negative'),
          ("@cianebeanie Scuse you, you're clearly the hoe initiating things here",'negative'),
          ("@PaulPaultaylor Cant be ass dont like hide out really might have few with my son and gf see wat there doing",'negative'),
          ("just got declined to join a feminist group because im not a girl",'negative'),
          ("@UrbanCityCowboy @W_Autism_Comm Perhaps but that is still no reason to treat other people like the shit on their shoes. SS broken already",'negative'),
          ("@MarkGrinter your point has little relevance. I know the difference between tax avoidance and tax evasion. Pension tax relief is not hidden.",'negative'),
          ("I really really hate that #DominosPizza ad....so fucking stupid!!!",'negative'),
          ("half of high end makeup products are only expensive because the brands want to have that persona smh",'negative'),
          ("@threeredkings O my nerves!!",'negative'),
          ("@aaroadwatch Big delays on N11 southbound near Kilmacanogue",'negative'),
          ("No winners dammit!!",'negative'),
          ("@___drievsy awful, awful, awful. I only saw him last August, fit and healthy, at Atonal.",'negative'),
          ("@matb_60 @Turtyforreal @hangballlouie Have a feeling this is how I'll end up feeling.",'negative'),
          ("@DeanoG1234 Why the fuck is that in your head",'negative'),
          ("Very sorry to hear about the tragic death of Fergie Kehoe, my thoughts are with his family this evening",'negative'),
          ("Calmness and chill tonight",'negative'),
          ("When SDLP had two Ministers looking after universities how many places did they add to Magee? - zero",'negative'),
          ("Btw I am hope I am not sounding arsy! I am not intending to be, still smarting from SS, nightmare",'negative'),
          ("@MarkGrinter my substantive point being David Milliband's father got slaughtered.",'negative'),
          ("@aligeekay It really is the worse thing about owning dogs,they don't live as long as us.I've been through this too many times,never easy",'negative'),
          ("@Sevcoholic @TheClumpany Realistically if Rangers total football wages exceed £50,000 per wk they will have massive problem lasting season",'negative'),
          ("@Channel4News @David_Cameron if you want to get rid of Dave, it's the ballot box every time!",'negative'),
          ("@Grantomac to think that @Martha1811 and I helped sponsor him. He's a disgrace, no idea. And I work in a call centre &amp; Martha f/t carer.",'negative'),
          ("@CadburyIreland my Saturday night has been ruined as my box of chocolate fingers were soft and stale when I opened them!!:-( :(",'negative'),
          ("I miss strolling around the playground and basketball court in the evening during IB days while watching the sunset..with Fats.",'negative'),
          ("@bet365 how come I haven't got any money back for these two then when they placed??",'negative'),
          ("How does equality work  #autism when people with #autism ignored whilst those with PhD's non autistic are listened to? #expertsbyexperience",'negative'),
          ("@mofohooker @Grntkmp fuck up raz",'negative'),
          ("@TopSixNextYear made himself look like a bad loser as well as a twat. Never liked him tho tbh",'negative'),
          ("I just got mint in my eye and I feel like I'm slowly going blind",'negative'),
          ("@David_Cameron It's not what's in yr tax returns that's the problem ... Oh, and the police protecting you today, WE paid for them",'negative'),
          ("I've got 6 months to loose as much weight as I can before my graduation. I need to feel beautiful and not hate my pictures",'negative'),
          ("@Arsenal @ElNennyM bit late for the best now league is well gone son",'negative'),
          ("Starbucks customer ‘taken aback’ by offensive message employee left on coffee cup",'negative'),
          ("@russellcrowe what they don't know for sure they make up... I'm waiting for you in the remake of Tootsie #challenge",'negative'),
          ("@mickobrien1 OK got it. It's  on BT/ESPN. Could they have buried it any deeper?",'negative'),
          ("@BTCare Hi! I've been waiting on customer support calling me back. But my internet has been down since 11pm last night.",'negative'),
          ("The Deluded GOIN fcuk wits are fighting with each other about good old pencil neck..",'negative'),
          ("It upsets me that Meghan Trainor is considered an artist...",'negative'),
          ("Pretty disappointing how little coverage tonight's Challenge Cup quarter final between Grenoble and Connacht has received outside Ireland.",'negative'),
          ("@SLATUKIP Can you not read Slatty? I wanted no involvement in some inane nonsense cyber rants from a teenager.",'negative'),
          ("@LFCLeo_ @AcademyLFC Are u joking mate ? He was getting whistled from his own fans after 8 mins , ok he won the corner but hardly been great",'negative'),
          ("I swear to good fuck if barca let me down I'm finished with football!",'negative'),
          ("im embarrassed for meghan trainor on the voice",'negative'),
          ("meghan trainor your song is  big fat NO! #thevoiceukFINAL",'negative'),
          ("Gosh I need more wine. Feeling sooooo fed up.",'negative'),
          ("I met young lad still undiagnosed but clearly #autism spectrum. He told me he didn't know what happiness felt like. He was 14 #failed",'negative'),
          ("@FollowsLove i cant even replyed  to louis messaged",'negative'),
          ("One dead and another seriously injured after two Haldon Hill crashes",'negative'),
          ("There are an army of people #autism who r disillusioned with the way we are ignored and misunderstood. Please join me in shifting the trend",'negative'),
          ("#BritainsGotTalent cant watch sword swallow`r yuk",'negative'),
          ("@SamHarrisOrg I don't consider myself enlightened I'm too full of anger and prejudice.",'negative'),
          ("Just got a text saying ma Taxi's been dispatched n arrived when a phoned it last night, yer a full day late mate",'negative'),
          ("Regret match cancelled tomorrow due to weather conditions.",'negative'),
          ("When people complain about how much they hate their jobs I'm like shut the fuck up at least you have a job.",'negative'),
          ("the blending on the right eye is ugly",'negative'),
          ("Actually ran out of the room can't watch #BGT",'negative'),
          ("This is mad, what the feck",'negative'),
          ("if u ever see Trisha irl im gonna kick her and her ma around",'negative'),
          ("you didn't go to physiology on Tuesday you liar",'negative'),
          ("@gamerprince1999 LMAO the perks of not being a KH only channel I get to talk about this fucked up shit lmao",'negative'),
          ("It irks me that you can get antibiotic eye drops over the counter but not ear drops",'negative'),
          ("Wessex 19 bus at my stop, was due to leave at 13:25 and now will just become the 13:45 instead. I can't believe I'm paying for this shit.",'negative'),
          ("@BloodyElbow trash fuckin move from Kimbo, considering how bad Dada came out of their fight, he might as well have died ffs",'negative'),
          ("I like Cloud @Migrator365 a lot, but they are woefully understaffed. Waiting 3 days for a support call response :(",'negative'),
          ("The next fella on a dating app, to ask me how or why I ended up on a dating app, is going to get a bollocking.  Same reason as you pal.",'negative'),
          ("Desperately alone and single",'negative'),
          ("Losing a pet leaves a big hole in your life and your home feels that little bit more empty",'negative'),
          ("@francismaloney5 @caulmick I don't like it.  LPT pays for nothing at the moment just another tax on us.. Gangsters comes to mind",'negative'),
          ("I would be totally freaked out if this was me!!!",'negative'),
          ("Genuinely hope Wessex goes out of business.",'negative'),
          ("Oh sorry Susanna, I hope you didn't need that arm. I might have some plasters in my pocket Producer face palms: Idiot.",'negative'),
          ("@Glaikitgit Tax returns are useless, they only show tax paid on declared income, not what you've got hidden in your Haven Hammock.",'negative'),
          ("I am so fucked for these exams",'negative'),
          ("Wouldn't be so bad if it was every once in a while but it's every single day",'negative'),
          ("Neither me or the Ground can take anymore rain #aquaFarming #beef",'negative'),
          ("Don't Waste your time on him/her anymore. Judging from the insuts he/she is not bright.",'negative'),
          ("You just ruined that for me!",'negative'),
          ("if they add it both will feel the pain in next election when ever it comes ..USC LPT IW all extra tax for nothing",'negative'),
          ("No 19 this morning and now there's a 19 in front of me that won't open its doors until 13:45 despite being here since 13:15",'negative'),
          ("A girl just used 'generally' instead of 'genuinely' and I can't describe my frustration",'negative'),
          ("@James_Yammouni I just had to Google who you are but I'm still confused. Are the Janoskians a One Direction or Jackass rip off?",'negative'),
          ("Fergie tells Danny Willett he had 8k on Spieth. Willett seems like a cocky fella, too",'negative'),
          ("I already hate &amp; resent the property tax. If they merge the water charge into the LPT,, I won't be answerable for my actions. #Dail #GE16",'negative'),
          ("Our experience with @AerLingus has been very disappointing. Next time insisting on @AirCanada. :(",'negative'),
          ("One of them was due to leave at 13.25 ffs what is going on",'negative'),
          ("@lizcrem he's basically saying you can be a nice person from the North side.",'negative'),
          ("Eurgh, I hate buses.",'negative'),
          ("No one wants to hear a pathetic fool after all.",'negative'),
          ("@Draigwenci They're STILL spreading the debunked Bernie can't break up the banks bullsh*t story, despite NYT debunking it (surprisingly).",'negative'),
          ("@SkepticalHusky As usual nowadays they're only showing excerpts even though the programme is an 1.30 long!",'negative'),
          ("can't believe i have to do my French speaking exam again because the machine didn't record it :(",'negative'),
          ("@meganlismag @thegaysay no it's because they dont treat minority groups fairly.",'negative'),
          ("Yeah it feels like they're reacting to some of the 'too dark' criticism. Kinda late though. Hope it isn't a mess.",'negative'),
          ("@BtrUSEducation Most children #autism may not even realise that the flickering light or buzzing computer is sending them #sensory meltdown",'negative'),
          ("now the hard work really starts",'negative'),
          ("@samsungforall I will fuckin knife you",'negative'),
          ("I draw the line at taking the fur of their dead bodies though.",'negative'),
          ("Danny Willett only went up 3 spots in the world for winning a major ffs its like there's the top 5 in the world then everyone else",'negative'),
          ("That is some depressing dull auld day out there.",'negative'),
          ("Moody and emotional",'negative'),
          ("No real surprises here given that deposit rates are at an all time low",'negative'),
          ("@miaamiamie pissin down here I wanna go to the sunshine bai",'negative'),
          ("@eircare I want to pay my bill but a late payment fee was supposed to be removed last week. It's still there. Can you resolve?",'negative'),
          ("That actually couldn't of went any worse hahahahah fuck sake I was speaking English and Spanish in there ahhahaha",'negative'),
          ("it's a tad expensive",'negative'),
          ("I have a really bad headache but my fam probably won't believe me",'negative'),
          ("@TwistedKinsale hi sorry I won't be able to dine with u this wkend as lads in the Blue Haven have let me down once again.See u another time!",'negative'),
          ("@MichealMartinTD @campaignforleo great idea amalgate water &amp; prop tax so tenants don't have to pay them. See where rents go then. Disaster!",'negative'),
          ("It's all about their big wages and pensions they don't care about me or you or homeless or sick just themselves",'negative'),
          ("Very worrying statistic @SCMagazineUK. Businesses must take responsibility for data #security, or risk a breach.",'negative'),
          ("It's Monday and I'm so done with this week already, I just want to drown myself in garlic bread and vodka",'negative'),
          ("I haven't done any speed work in months... I have work to do",'negative'),
          ("@BtrUSEducation For many children #autism spectrum school is a #sensory nightmare that sends many into #meltdown #shutdown",'negative'),
          ("Why do people just sit down accross from you when there's no free seats without asking like I COULD HAVE FRIENDS",'negative'),
          ("My bank account nor my stomach can afford Nando's but here I am",'negative'),
          ("Sickens me to the stomach!!",'negative'),
          ("Poor and fat",'negative'),
          ("bah! So jealous to have missed these!",'negative'),
          ("Am going to ma bed before today gets any fkn worse",'negative'),
          ("Whoever said uni years are the best years of your life, clearly never went to uni",'negative'),
          ("@ejbren this fellas going cheap lol",'negative'),
          ("Used to like airports until @Drew_Mendoza1 ruined them",'negative'),
          ("@meganlismag @thegaysay no they pick and chose verses from bible. My religion is not why I won't vote for them I'm not a catholic for record",'negative'),
          ("@FAICoachEd is there any chance of showing courses further then the month of April?? Seriously....",'negative'),
          ("Can't say I agree with criminalising men over abortions, surely we should be working on decriminalising abortion not criminalising further",'negative'),
          ("@Seanofthesouth McNarry would shoot them down.",'negative'),
          ("@cathyby @bowmanthebard why would it? Automatic assumptions that disparities are bad, permanent or alleviatable not defendable",'negative'),
          ("@ovrplyd take it back",'negative'),
          ("Chilled to the bone at home",'negative'),
          ("Just give up. This person's dense as the densest fog.",'negative')]
