tweets = [("no probs girl...where were you tonight??",'neutral'),
          ("No Terry Wogan on eurovision commentary",'neutral'),
          ("where's mine",'neutral'),
          ("how's the weather?",'neutral'),
          ("looks traditional and spicy. no knowledge abt korean food",'neutral'),
          ("Your life does not get better by chance, it gets better by change.",'neutral'),
          ("@LincsSkies @DSunsets reminds of one taken of the river #Witham near #Bardney a few years ago",'neutral'),
          ("#ZSMedics #ZSHQ Medics yoor Matron needs yoo! Staff needed in Welsh Dragon Mission 17/4  Get yer bedpans reddy",'neutral'),
          ("Cometh the hour, cometh the Ulsterman! Let's go @McIlroyRory #Masters2016",'neutral'),
          ("If anybody wants a stream for the boxing here u go",'neutral'),
          ("Does anybody enjoy Montys commentary or analysis?",'neutral'),
          ("@sportingrelic I hear ya, but ya never know and there history precedes them... ",'neutral'),
          ("Sets a dangerous precedent and should be frowned upon.",'neutral'),
          ("@clareisainmdumb Genuinely the thing that I miss the most about Trinity is the proximity to burritos in general",'neutral'),
          ("@StreamPlanet what's the chance of getting Grenoble v Connacht Rugby tonight is on bt sport espn and bein fr 3, know it's a big ask",'neutral'),
          ("If liberal democracies support racist and xenophobic policies, how can they promote human rights?",'neutral'),
          ("Children #autism need to be dragged countless appointments assessments &amp; meetings. Try telling your employer you need 2 days week off work?",'neutral'),
          ("Life is to be enjoyed, not endured.",'neutral'),
          ("you can see this one growing as you watch it #clouds #Cornwall",'neutral'),
          ("Why can't we all just support each other? Just because I wouldn't wear a pair of shorts with my arse peeking out doesn't mean I don't",'neutral'),
          ("Today's team photo",'neutral'),
          ("@threeredkings Def. Very professionally run today... I've no choice now!!!! ",'neutral'),
          ("Mix &amp; Vote for the Best",'neutral'),
          ("Going on #private for a while guys.",'neutral'),
          ("@andyAV1 crazy!!!! Needs stopped",'neutral'),
          ("@jonnyfallon which panel",'neutral'),
          ("@L0RD_H @Victoria1867 @AwayDaySleepers I'm not sure  British Transport police will stand for that",'neutral'),
          ("Just ordered another spicebag...",'neutral'),
          ("@AapPower story with it",'neutral'),
          ("Our new range of Fairy Doors.",'neutral'),
          ("#Dublin1916 - Drinking a Children of the Revolution by @WWolfBrewery @ Dublin Castle",'neutral'),
          ("Aintree has got all the bookies there money back from Cheltenham this week.",'neutral'),
          ("@PARRY1956 do you have a link to your source",'neutral'),
          ("@cenkuygur @JetBlue Just chill, fella. Service on airlines is now history",'neutral'),
          ("I'm at Abbeygormican",'neutral'),
          ("#bgt is now trending in United Kingdom",'neutral'),
          ("#epicdanceoff is now trending in United",'neutral'),
          ("#thevoiceukfinal is now trending in United",'neutral'),
          ("#britainsgottalent is now trending in United",'neutral'),
          ("#Ireland...Where parking on double yellow lines is allowed as long as mass is on.",'neutral'),
          ("Mr Piketty enters the migration debate in Europe",'neutral'),
          ("@patkirley Another new Opel Mokka 1.6CDTi sold",'neutral'),
          ("@DermalogicaUK DETOX Pack €100, save €20 * Limited offer",'neutral'),
          ("Jose Mourinho rejects Syria coaching job - agent Jorge Mendes I wonder why ???",'neutral'),
          ("@BelgianKeeper I'm pretty certain that it was Benteke",'neutral'),
          ("My 5 year old cousin made a list of everyone who didn't give her a present for her birthday",'neutral'),
          ("Dublin please.",'neutral'),
          ("Anyone tell me if DIT Kevin St. Is one building or a few?",'neutral'),
          ("Exclaiming shock upon seeing how bright it is so late in the evening, even though it happens every. single. year...",'neutral'),
          ("@mand_brun britains got talent",'neutral'),
          ("@marczak Agreed. He followed it up with a @Storify'd post which is easier to read, but he's doing himself no favors.",'neutral'),
          ("Argument I'm having with my sister. Are chokers still in fashion",'neutral'),
          ("@Conjob123 @leeoxS6 the way the course is playing not so sure about that",'neutral'),
          ("@Geokypan And she lifts everyone's phone and does selfies",'neutral'),
          ("Does anyone reckon if I had a sob story for #BGT and stole jokes from Banter ",'neutral'),
          ("Lines would I get through?",'neutral'),
          ("@lolIirot that's what idg, it's a hairstyle, that's like saying 'oh you can't eat pasta it's not from ur country'???",'neutral'),
          ("Sell ya nudes to random dudes",'neutral'),
          ("I say I'm not drinking tonight but fact by 11.30 I'll have a sambuca in hand",'neutral'),
          ("Thought: why all the campaign to 'cute' autism but not dyslexia?",'neutral'),
          ("How much meal",'neutral'),
          ("Everyone needs a @conheg in their life",'neutral'),
          ("was paying players from his own account why no highlighting of it",'neutral'),
          ("Do I wake them?!",'neutral'),
          ("@KrWonderboobs 60+ today so far",'neutral'),
          ("An 11 year old can't be funny, they just don't have the experience. Comedy is created by pushing boundaries or seeing things in a new way.",'neutral'),
          ("Our evening in enniskillen is at my sister's house, @kirstieradio, for our 2nd come dine with me of 2016,",'neutral'),
          ("@GTCost @brianmlucey Suns out guns out.",'neutral'),
          ("@christine_gooch Did you see anybody you know John?",'neutral'),
          ("@ThreeCare why is there no service in Limerick city ?",'neutral'),
          ("@karenspics18 hey babe how are you",'neutral'),
          ("Yep, @kfc has ran out of chicken...",'neutral'),
          ("Does the present Archbishop of Canterbury being born out of wedlock mean that marriage doesn't matter any longer in the Church of England ?",'neutral'),
          ("no signal until tomorrow, cya buddies!",'neutral'),
          ("@Gair06 @MidasForTheGold I like his positive approach but I agree he took his time to change the overall shape of the team.",'neutral'),
          ("@ClairAlice92 oh yeah hopefully it will be a great one, not just a second round knockout or something like that",'neutral'),
          ("@McIlroyRory starting as he means to go on #TheMasters #Rors #goonrory",'neutral'),
          ("In tmrw's paper @NoelMcMeel tells @aligordonx why his diners at home are just as important as Barack Obama.",'neutral'),
          ("@bwsrunaway we need to go",'neutral'),
          ("Not that it’s any of my business nor implying anything. But Helen Mirren manages.",'neutral'),
          ("It's only a proper Major when you see #kenonthecourse #BBCGolf missed it the last 2 days watching the American coverage",'neutral'),
          ("Oyarzabal is going places",'neutral'),
          ("Ards shopping centre.",'neutral'),
          ("100,000 visitors a week.",'neutral'),
          ("1,200 car parking spaces.",'neutral'),
          ("0 bike racks.",'neutral'),
          ("Just posted a photo @ Arbroath, Angus",'neutral'),
          ("@leannedemps Check your messenger, missy",'neutral'),
          ("Dolling up an old tired stairs with a kit from Ballingeary joinery",'neutral'),
          ("@ToyotaFactory I quite like the fourth-generation Prius. But when do I start seeing them in the streets of Leicester?",'neutral'),
          ("It's rather weird, seeing the film set for a major TV show on a sleepy little road you always associate the the bus to Primary School.",'neutral'),
          ("Imagine doing the leaving cert :P",'neutral'),
          ("@KloppNormalOne same I turned on city game and screen turning funny colour",'neutral'),
          ("@Emilyxxxxx1D i am limited so i message you on the group chat",'neutral'),
          ("@ToyotaFactory Please visit my Twitter page and check, for example, my BBC link.",'neutral'),
          ("Light travels faster than sound. This is why some people appear bright until you hear them speak",'neutral'),
          ("@cyclingruss back open Wen Week!",'neutral'),
          ("Done and dusted 2 hrs ago Couple these to sleep",'neutral'),
          ("getting close to 5k",'neutral'),
          ("@CurlySportsFan Looking at the wind I suspect Rory may have the advantage, looks like tough conditions",'neutral'),
          ("Look at his paw omg",'neutral'),
          ("@tinturholsteins @Hylo67 @brianrushe81 @farmerfarrell @Jimmulh Some things are best left unsaid ....",'neutral'),
          ("Wind 2.0 mph E. Barometer 1002.65 mb, Rising Rapidly. Temperature 7.0 °C. Rain today 0.2 mm. Humidity 69%",'neutral'),
          ("@eugene_gaughan they do told sense on there....",'neutral'),
          ("@louclarkeradio Were they near each other ?",'neutral'),
          ("We might have had a red card as Ayman Ben Mohammed lashes out,  only a yellow given.",'neutral'),
          ("Wind 13 mph SE. Barometer 1006.71 mb, Rising. Temperature 7.1 °C. Rain today 1.8mm. Humidity 94%",'neutral'),
          ("@Greg1954 I'm on the Hobgoblin.",'neutral'),
          ("@exitthelemming for some reason my brain saw them as cupcakes. Really big artichoke shaped cupcakes.",'neutral'),
          ("'everything i do, ragnar, is for you' floki c'ha la cotta che scotta #vikings",'neutral'),
          ("@ToyotaMH_UK Please visit my Twitter page and check, for example, my BBC link.",'neutral'),
          ("something in it for everyone to like #SP16",'neutral'),
          ("@damienrea up for this again?",'neutral'),
          ("Dog froyo is on sale in Cork. Great idea from yogies.ie! What would Vera choose: froyo or cat? #veraschoice",'neutral'),
          ("@CleaverGavin @SBIdotcom @lorrainecleaver At the much work backed sweep stake, forget was it was for 3rd but I know it was £300 for 1st",'neutral'),
          ("@missnaomipeach ah that's true enough I agree",'neutral'),
          ("Can't beat a bit if glitter",'neutral'),
          ("@Emilyxxxxx1D sorry tell the others please",'neutral'),
          ("#vinb @rte @DailyPlato The 'Treasures of the Indus.' and Sona Datta's wonderful disclosure of the antiquity of Hinduism need to be revisited",'neutral'),
          ("@bet365 hi, I put money on Matsuyama to go under par on hole 2 at the masters, which he did and it's been settled as a loss, why?",'neutral'),
          ("am I seeing things? Barcelona down 1-0 to Sociedad #scenes",'neutral'),
          ("@enterthevoid66 no, it's not.",'neutral'),
          ("@ToyotaGB When does the C-HR go on sale in the UK?",'neutral'),
          ("@stujak74 Is that you???",'neutral'),
          ("Did she just",'neutral'),
          ("The sun shone, having no alternative, on the nothing new. Sam Beckett. An original Twitter poet. His bridge (Dublin)",'neutral'),
          ("@Brownbrock @HelenPUPNI @OfficialPUP @cllrjohnkyle @pup_east would think its a free vote allowing folk 2 make up their own minds in D party",'neutral'),
          ("What's the story @ComicBook you had a link saying #DoctorStrange trailer released online... It was gone in seconds,  anyone? #Marvel",'neutral'),
          ("You would see some people in that roosters gaf it's jammed tasty gaf tho all the same",'neutral'),
          ("It's actually snowing or sleeting wtf",'neutral'),
          ("Martin Gringo gets ready tell a story....  Los Gringos back in 'da hood'",'neutral'),
          ("Amanda has a rip in her dress #bgt",'neutral'),
          ("@lolIirot exactly, I understand that, and I'd understand if they were giving out to someone who discriminates against poc",'neutral'),
          ("Amanda basically just gave her 12-year-old self the gold buzzer, didn't she? #BGT",'neutral'),
          ("Interesting fact this morning on Saturday kitchen",'neutral'),
          ("#BritainsGotTalent i knew it amanda pressed her golden nob",'neutral'),
          ("McLowry +4 today. Not happening for  Steve today.",'neutral'),
          ("Mum: OMG is her dress ripped Me: No mum, it's the design Mum: You sure? It looks like she's stood on it and it ripped! lool #BGT",'neutral'),
          ("I have no idea what the golden buzzer means tho what is it",'neutral'),
          ("What does the gold confetti mean? #BGT",'neutral'),
          ("@ToyotaGB Please visit my Twitter page and check, for example, my BBC link.",'neutral'),
          ("Aspect Software: Software Engineer - Cloud Test Automation",'neutral'),
          ("RYA powerboat instructor course. Sure what else would ya be doing on a Saturday evening",'neutral'),
          ("Getting to Slovenia is not an easy task",'neutral'),
          ("@TomWhelan19 I've no idea - didn't catch it.",'neutral'),
          ("@David_Pants Nah. Sucking the gas out of the radiator",'neutral'),
          ("@BonnieBT13 Well it was dads before mum met him so it mite be Neely dat old!!",'neutral'),
          ("@bfcdublin take the lead as they finish off what must en their tenth corner, Byrne with the header.",'neutral'),
          ("I thought ye might like the messy ones!",'neutral'),
          ("Will do guys",'neutral'),
          ("@thatboiyiddo def kevin street i have an office number! just don't know what side. Its near the chemistry labs if you've ever seen them?",'neutral'),
          ("Chilli cheese nachos, chips, scampi, more chips, pints, fajitas, even more chips, chocolate ice cream, apple pie",'neutral'),
          ("We're not on our way back",'neutral'),
          ("@DJCC_Coach know of any runs from Arbroath moro? New member asking, there is one in Forfar",'neutral'),
          ("But how would it fare in the NHTSA and IIHS tests?",'neutral'),
          ("@ArianaGrande mom when is visual two?",'neutral'),
          ("#WKUStudyAbroad student @sherahdevore at the top of King Arthurs Seat in Edinburgh, Scotland!…",'neutral'),
          ("Liked Rita Ann Higgins William Faulkner quote on The Poetry Programme, 'The past is never dead, it's not even past.'",'neutral'),
          ("@Lughson When SDLP held the Ministry for building houses in the North how many did they build?",'neutral'),
          ("@Toyota Please visit my Twitter page and check, for example, my BBC link.",'neutral'),
          ("This is too relevant to my life",'neutral'),
          ("Who would you vote for? #TheVoice #voiceukfinal",'neutral'),
          ("@W_PIPPY be careful Stan Collymore was at the game",'neutral'),
          ("Bald Headed Woman by The Kinks is #nowplaying in Robinsons, Belfast.",'neutral'),
          ("@pup_east if id my way id have us out before midnight mate",'neutral'),
          ("@mickobrien1 Any idea how to find the Connacht game. Supposed to be on BT but I can't  find it.",'neutral'),
          ("@PrinceWatercres heres the link",'neutral'),
          ("Honeyed chicken and mushroom pot",'neutral'),
          ("Do you know where I left my car keys? #askbutch",'neutral'),
          ("@sioframoley are you serious",'neutral'),
          ("@Jahloon @bernieforkin Dublin, didn't ask the price they were very nonchalant about it. I'll be in again ,they've loads of gear",'neutral'),
          ("Karma as they say is a....",'neutral'),
          ("I realize I use spongebob references a lot when I'm around ppl who never watched it bc I literally say that's from spongebob every 4 mins",'neutral'),
          ("A dawn session bass",'neutral'),
          ("Plenty of updates please.",'neutral'),
          ("@Sezskis24 New Nightmare. A very underrated film.",'neutral'),
          ("#Saturdaze about to take effect",'neutral'),
          ("@AskPaddyPower I backed Aguero to score first so Im jus wondering when does free bet get added back onto my account",'neutral'),
          ("Why aren't we funding this??",'neutral'),
          ("What happens when you punch a wall sideways",'neutral'),
          ("@LibraryCampaign got a big big thing the 20th so not sure but will email though",'neutral'),
          ("@paul_gavan you keep talking about the past",'neutral'),
          ("@entertainmentIE Earning £10 million really is hard work.",'neutral'),
          ("We haven't received our census forms. How do you get them?",'neutral'),
          ("@tweetbot please please give us an option other than small and large for image previews. These are way too big",'neutral'),
          ("@Shanemcf1 Ah come on man you know exactly what I mean about",'neutral'),
          ("@CheeseburgerROH is it bad that I now want to watch more #FMW",'neutral'),
          ("@Brian_Holden @ghostydiddy did yous have fun in Ireland last month? #AVPM7",'neutral'),
          ("@voiceUKbbc Lydia or Kevin - can't decide who's going to win!",'neutral'),
          ("My Twitter app timeline is still on Friday night.. Tweetbot FTW",'neutral'),
          ("Ok the touch on my phone was on its period until I deleted @Snapchat story there?",'neutral'),
          ("@enterthevoid66 she grew up rich af...maybe they had some bourgeois name for it.",'neutral'),
          ("@JoeManager which band member found the girl? #VampsFoundAGirl",'neutral'),
          ("Give us the quick tour of the wine shop she said! No bother we said.. #sligo #wine #sligofoodtrail",'neutral'),
          ("@Shanemcf1 @VoteHollandSF @Lughson SF held education transformed schools right across North",'neutral'),
          ("@dnyobrn she probably only doing 5 or 6 songs. Reckon they'd do a duet they're mates I think",'neutral'),
          ("Easy Love by Sigala is #nowplaying in Trafalgar, Hednesford.",'neutral'),
          ("I'm at The Trinity in Dublin",'neutral'),
          ("@Shy_Teds not watching.  Is someone singing a song?",'neutral'),
          ("I just need someone to come get drunk with me",'neutral'),
          ("1-0 Milan no it wasn't Balotelli but he did win the corner",'neutral'),
          ("@NudeAudio Hey, now that you are seemingly back in business - any chance you can replace my broken Super M that I contacted about a year ago",'neutral'),
          ("@btsportmotogp I thought he was bonkers. Maybe he was on to something. 2of2",'neutral'),
          ("@AlanKSTS Jeremy Corbyn has checked in at ten downing street no need for elections anymore",'neutral'),
          ("@marcdarcylondon Hey guy's, looking to buy the tan crombie says 30% off on the ad but as soon as I go to checkout its up at £99.99 again?",'neutral'),
          ("niall can you talking in the group chat please i cant answer",'neutral'),
          ("He's playing in Tallaght tonight, Mickey just requested a bitta @MarkMcCabeIE",'neutral'),
          ("Our new range of flower doors.",'neutral'),
          ("ur right SF never held that Ministry but SDLP had 2 Ministers of DEL how many places did they add",'neutral'),
          ("@JoeManager did you cut your hair up?",'neutral'),
          ("women all over the country be glued to watch anthony tonite beast",'neutral'),
          ("@LimerickMitch you know anyone doing updates on the game?",'neutral'),
          ("@karenspics18 hey babe like you are you in coventry",'neutral'),
          ("Fanks pal. W/wam was brill. Now in",'neutral'),
          ("my thoughts exactly!!",'neutral'),
          ("Just put a tenner in a bucket to watch @Joe_Panama jiggle I feel dirty.",'neutral'),
          ("just ate half a bowl of ravioli... with ham in it...",'neutral'),
          ("@TopSixNextYear bit longer than your cup defence",'neutral'),
          ("@CSFTT The FAI have stopped glamour fixtures in Limerick before , agreement with Aviva (,This agreement may have expired )",'neutral'),
          ("I'm in TGI Friday's Victoria Square with @EoghanMcManus and others.",'neutral'),
          ("@SaorAgusGaelach I thought @EndaKennyTD called @fiannafailparty a crowd of whingers pre-election. What the corrupt will do to stay in power?",'neutral'),
          ("Put your money away. That's my fish.",'neutral'),
          ("@threeredkings @Irishbiltong who in the name of baby Jesus has that channel",'neutral'),
          ("Got sum #dank cheese on deck",'neutral'),
          ("@dnyobrn very true. very philosophical",'neutral'),
          ("The Dark Matt Rises.",'neutral'),
          ("@Shanemcf1 @VoteHollandSF @Lughson Simply question how many places did the 2 SDLP Ministers add to Magee? can you answer it please",'neutral'),
          ("Gettin far to emosh over King Kong on my break wow",'neutral'),
          ("New post from me. They are rare these days.",'neutral'),
          ("@DavidOShelton Gives a whole new meaning to getting steamed!!",'neutral'),
          ("@JackRFullam we all have our flaws",'neutral'),
          ("Messi having one.",'neutral'),
          ("the county side can have its perks sometimes",'neutral'),
          ("There's actually some creatures on this program",'neutral'),
          ("@enginewatcher totally agree with you what happens behind closed doors stays behind closed doors to the detriment of many families #shocking",'neutral'),
          ("i cant answer you guys so please stop it",'neutral'),
          ("I ate so much cheesy mashed potatoes and beans I might explode",'neutral'),
          ("eats a buttons ice cream",'neutral'),
          ("That's a totally different film",'neutral'),
          ("I need to make this towel idea happen.",'neutral'),
          ("Sadly conformity is too often the road to advancement and complacency the way to survival",'neutral'),
          ("Not that your admitting to anyway",'neutral'),
          ("@That_AO book it soon !",'neutral'),
          ("@fabfoodcork yes that's true, not good. And so many new clean eating cookbooks are loaded with recipes using medjool dates. What to do?",'neutral'),
          ("can't take credit for riding her there, that's Boab's cousin.",'neutral'),
          ("We take for granted, what is in front of You?",'neutral'),
          ("aren't we all!",'neutral'),
          ("@PhilipTyndall a certain weigh when eating 1kg.",'neutral'),
          ("yep but he knows it !!!",'neutral'),
          ("@dungarvanbrewco @TomSham . In Murphy's for 1st time, drinking rebel red. No DBC. Why ?",'neutral'),
          ("@Pollylwh Me too . I did have a weepy moment when my George went to visit to #carnegieoccupation in the week",'neutral'),
          ("A few short days on twitter and @SocCultGeog has 265 followers. It takes some of us years of bad puns to get that popular.",'neutral'),
          ("@theLatchicokid They really do think they are some sort of royalty, even warning journalists... I invite you to be wary",'neutral'),
          ("Went to see my Dad's new Highland cows",'neutral'),
          ("Think my next tattoo is gonna be like this but gonna change it around. ",'neutral'),
          ("And then you get offered a knighthood and you think- I won't bother my arse.",'neutral'),
          ("Wish I had a better camera! Starting the night shift",'neutral'),
          ("Am I a pyscho if a log onto someone's snapchat n see something from another girl, so a snap her?? Is that so bad ??",'neutral'),
          ("Download it now at",'neutral'),
          ("goes at 45* so ya can do all kinds of wizardry!",'neutral'),
          ("I it was my choice to part with",'neutral'),
          ("@DeclanGorman1 Tenni is waiting on us",'neutral'),
          ("Just made my own organised calendar for the next month for uni/work/social life.",'neutral'),
          ("Turns out there's no space for social life though",'neutral'),
          ("@KarlaMNL If you pay for my air fair I'll come right now lol",'neutral'),
          ("A porn you made in your younger days?",'neutral'),
          ("@queencrean can u bring me",'neutral'),
          ("In case u missed it, here is the selfie",'neutral'),
          ("@Shanemcf1 @VoteHollandSF @Lughson SDLP joined with Unionist parties over selection sez they had solution that was 2014 still waiting for it",'neutral'),
          ("@ZoeTheBall just wondering where did you get your shirt on the show tonight ??",'neutral'),
          ("@jabberworks @malorieblackman We happened to be in the car and caught a bit- kids now asking if we can visit the exh at Compton Verney!",'neutral'),
          ("@issassin Yeah. they really should have a 'number of times caught out of position' stat..",'neutral'),
          ("David Livingstone on Sky Sports with this absolute classic one liner on Bryson's balls.",'neutral'),
          ("Drinking an IPA",'neutral'),
          ("You just came right out and said it.",'neutral'),
          ("@SteveHopcroft Ger from st Kevins that lad who played for WBA today would he have been at the academy cup?",'neutral'),
          ("meghan trainor is on the voice gross",'neutral'),
          ("@Martha1811 maybe if Gavin had a couple of shifts on the phones beside me he would realise he has a dream job",'neutral'),
          ("@SarahHelenClose and I'm going as a raccoon",'neutral'),
          ("What's his name ?",'neutral'),
          ("i'd only go to District 8 if I could sit in the back somewhere like a cunt and drink my own shoulder and not dance to be honest",'neutral'),
          ("@Shanemcf1 @VoteHollandSF @Lughson like the 7 page plan they claim they brought forward in December still hasnt seen light of day",'neutral'),
          ("are you ok",'neutral'),
          ("It's Boab's hobby really, I just give him a hand. We'll get the gelding and filly out locally",'neutral'),
          ("is up! Everyone be quiet and listen!",'neutral'),
          ("missed that tip this morning -where's the party ?",'neutral'),
          ("@GarethCambridge have u ever seen barca play so bad?",'neutral'),
          ("So uh. @OWN_1883 had his sat nav set to Cardiff. Minor route failure. Back on course.",'neutral'),
          ("En route to spin at Shenanigans Venue - The Promenade",'neutral'),
          ("Need me to spell it out for ya lol",'neutral'),
          ("gone to ground? League over.",'neutral'),
          ("Good evening #Dublin! Sun will set in 30 minutes",'neutral'),
          ("Is there a full moon @barrabest?",'neutral'),
          ("I don't mind if they leave his return go for another while.",'neutral'),
          ("our @miicork ball chair is now on stage to address the room",'neutral'),
          ("@enterthevoid66 well, yeah... we mostly have continental breakfasts.",'neutral'),
          ("These bt guys have clearly never watched Connacht before. Connacht playing the way they do every game.",'neutral'),
          ("Covered a lot of ground the last few days",'neutral'),
          ("Let me show you around Paradise",'neutral'),
          ("Private personalised tours 1-8 pax",'neutral'),
          ("Is anyone else feeling?",'neutral'),
          ("Why wouldn't you vote for Hilary?",'neutral'),
          ("Suicide Squad trailer #1 and all the director comments about how scary Leto is, sure paint a different picture than trailer #2 and #3.",'neutral'),
          ("gotta upload my pics n videos from the weekend",'neutral'),
          ("Rate a early finish",'neutral'),
          ("#communions can be very #expensive so remember to #budget and here are some ways to #save",'neutral'),
          ("Win Prizes! RT + Follow to be in for a chance to win!",'neutral'),
          ("@GAA_USA  Check us out.. we are 1 of 5 Official GAA Charity Partner for 2016",'neutral'),
          ("They used to punch each other around",'neutral'),
          ("Making our own story. And of course the magic book is important as well at that time.",'neutral'),
          ("@mmcuriee I'd prefer Lupin but I'd do better under McGonagall",'neutral'),
          ("apologies, change of date for BURNIN UP, it's now FRIDAY 22ND APRIL @TGSDublin &amp; NOT this Fri, hope to see ya there",'neutral'),
          ("If you missed @naomi_long on BBC Sunday Politics you can catch it here",'neutral'),
          ("@mmcuriee also did you see the Fantastic Beasts trailer",'neutral'),
          ("Off for Lunch",'neutral'),
          ("The pimple on my head resembles the one from the Amanda show that wore the cowboy hat",'neutral'),
          ("Next year, without a shadow of a doubt, I'll be buying a First bus pass instead of a Wessex.",'neutral'),
          ("Maybe people will start to understand me more with this photo.",'neutral'),
          ("do you ever walk into a bathroom and not know what gender you are?",'neutral'),
          ("@WestComms are you joining us at Roadford again tomorrow?",'neutral'),
          ("@czarkaztik oh ok. I don't like the colour though red suit it better",'neutral'),
          ("Please help a graduate student by taking this survey on #Bratislava",'neutral'),
          ("One will be taking on revenue if it happens(is that correct)",'neutral'),
          ("PSG Officiel, @psg_inside is now trending in Ireland",'neutral'),
          ("RT @minkcompany: Last chance to enter our #FreebieFriday #Giveaway!",'neutral'),
          ("Jim Goldie has the first three in the market in the seller later.",'neutral'),
          ("I really hope this app is right about the weather.",'neutral'),
          ("Found a loaf of cat in my bedroom last",'neutral'),
          ("@ireland Meditation and deep breaths.",'neutral'),
          ("The official twitter account for the UL Hospital Group @ULHospitals, is now live!",'neutral'),
          ("@BTCare hi, if I take out TV with you, what will I get I.e channels??",'neutral'),
          ("#Sussex stables job. Black plastic internals with external doors.",'neutral'),
          ("Hypocrite by The Specials is #nowplaying in Robinsons, Belfast.",'neutral'),
          ("Check out our new promo video recorded live at the Picturedrome, Northampton!",'neutral'),
          ("Our website has made semi finalist",'neutral'),
          ("Does this not bring revenue into the equation",'neutral'),
          ("@myhermes hi, can we get a VAT invoice for all dispatched good. Is it possible on site?",'neutral'),
          ("Do you use high quality swing tags?? Please click the following link",'neutral'),
          ("@Draigwenci Is it wrong then if I call them names when they refuse to accept facts &amp; keep peddling lies?",'neutral'),
          ("Got myself a @caocigars Flathead sampler, the only way l could find some of them.",'neutral'),
          ("look who's on twitter",'neutral'),
          ("This is the man that is reportedly taking #BrianJohnston's place in @acdc? I think not!",'neutral'),
          ("@johnhidd not that tough,Its home Its not work",'neutral'),
          ("First concert I have missed since 1989. Any for Sale - let me know.",'neutral'),
          ("All my 419 stand up. Only Nigerians will get this tweet",'neutral'),
          ("here's your prize. Sneak peek at new xmen movie!!",'neutral'),
          ("@Iamyasminkhan Sorry, I think you were too evasive on the chastisement question.",'neutral'),
          ("I've no brief for Baroness Cox - she's no liberal",'neutral'),
          ("sadly can't find a pic but here is something similar.",'neutral'),
          ("it prob does.. Let them look after #Panama gentlemen and hit the poorest of People",'neutral'),
          ("Well this weather will sort the hardy from the not-so-hardy!",'neutral'),
          ("Might need a hot whiskey.",'neutral'),
          ("I paid money for these 2 apps , so let my selfies shine from now on",'neutral'),
          ("Hey guys wanna come to my poetry slam and we can get avocado smoothies afterwards",'neutral'),
          ("@brandartillery Can @DubCityCouncil not get their ex bin collectors to take them down? How were those guys re employed?",'neutral'),
          ("@CadburyIreland why can't the egg be made all year round now that Cadbury have dropped the Easter out of it cause I'd buy all year round",'neutral'),
          ("Interested in health social care policies? Going to this Tom night - maybe ask a few Q's",'neutral'),
          ("@werderbremen_en any tickets left for the Wolfsburg game?",'neutral'),
          ("in the mean time Charles.....",'neutral'),
          ("What do you know about my ends?",'neutral'),
          ("Is it just me who thinks Rufus from Gossip Girl kinda looks like Ezra for Pretty Little Liars?",'neutral'),
          ("Need to get you a draught pint in Dublin again!",'neutral'),
          ("@JamesMathewPine My theatre group are doing a production of Sweeney Todd in the red building next to where you and Mike live",'neutral'),
          ("@HaggisAdele I've never run that fast in my life. I think I would probably die!!!",'neutral'),
          ("The news #cotswoldsgardenroute leaflet has arrived &amp; will be at #highgrove event this week",'neutral'),
          ("We couldn't resist sharing this",'neutral'),
          ("Nutrition 4 Life seminar on Sat 14th May in Ennis",'neutral'),
          ("Life is not about searching for things that could be found. Its about letting the unexpected…",'neutral'),
          ("Any of your associates / friends at #filf 2016 #DublinCastle over week-end?",'neutral'),
          ("Can you recommend anyone for this #job? Medical Sales Representatives - West Of Ireland",'neutral'),
          ("aye two recent Hogan ones particularly",'neutral'),
          ("Thread of threads of threads",'neutral'),
          ("Open Call Deadline April 30th",'neutral'),
          ("@JANUSZCZAK read your article on taking control of your health.",'neutral'),
          ("I am on that path.",'neutral'),
          ("@BtrUSEducation Most children with #autism spectrum will respond to the teacher and not the subject. Preferring soft gentle tone voice",'neutral'),
          ("I'm in @writing_ie today talking about externalising inspiration and where ideas come from! #KOTBD #writing",'neutral'),
          ("My point is ,once revenue becomes involved...we will pay",'neutral'),
          ("SF advised ppl not to pay house charge.Changed their tune",'neutral'),
          ("@TSBible @EddieHearn let's not get carried away either. Ali had to beat Liston.",'neutral'),
          ("one of the major drivers of inequality is the link between voter registration and access to finance",'neutral'),
          ("Naive to believe that money does not play a part.",'neutral'),
          ("Want to Ask a politician abt health &amp; social care NI ... What r ur questions?",'neutral'),
          ("Let me know an I'll ask",'neutral'),
          ("@mmcuriee I had a Spanish teacher in GCSE who managed to mix both",'neutral'),
          ("I'm reading Marlon Brando's acting bio.",'neutral'),
          ("@KZapponeTD @bryansixone here's me being a journalist. Note the wide array of sources",'neutral'),
          ("Got selfie stick out yer I have",'neutral'),
          ("Holidays - clouds and little people",'neutral'),
          ("where did you end up last night Shauna",'neutral'),
          ("Meodie Bonanno: Queen of the run on tweets.",'neutral'),
          ("Do either of you fancy running Rhal pace?",'neutral'),
          ("i can't believe sehunnie's birthday is in less than three hours throw me off a roof",'neutral'),
          ("@dearbhla_mcd ?i promised not to tell?. But lion insisted he tell ? Or else??",'neutral'),
          ("have I lost a day?",'neutral'),
          ("I wish it were Toothy's birthday again",'neutral'),
          ("@OLBG Depends on the ground really - anything with good in it I'd have no doubt about Cue Card staying so that for me!",'neutral'),
          ("Our 16 startups have a packed week of mentoring ahead",'neutral'),
          ("@MartinHGames Seems you disturbed its mating display, Martin...",'neutral'),
          ("Get 25% off with new code",'neutral'),
          ("Would love to have a smoke in memory of @OfficialMrNice right now, but I'm going on @TheLastWord to talk about him later. So I'll wait...",'neutral'),
          ("Alphabet-owned robot start-up shows off peculiar bipedal bot that looks like something from Star Wars",'neutral'),
          ("So if Noahs Ark #dental practice in Fowey Cornwall can be an excellent of model of practice #autism spectrum why can't they all? #brilliant",'neutral'),
          ("Performing in Whelans tonight for @CherryComedy",'neutral'),
          ("@SkepticalHusky Better than here! I honestly don't remember when I saw a classical music programme on @rte.. A proper one not watered down.",'neutral'),
          ("@brendan_m96 bro u took my picture",'neutral'),
          ("@johnhidd sure if you put the work in you should get the recognition anywhere",'neutral'),
          ("Want to join #TeamTeeling? Check out our @JobbioJobsIRE for all the details!",'neutral'),
          ("With #golf a hot topic this weekend, see why #Ireland…",'neutral'),
          ("Watch our 2yo Intikhab filly strut her stuff ahead of the Doncaster breezeups",'neutral'),
          ("Me ma sent me a picture of me when I was 14 in dickies and Timbs. There wasn't a hope in hell I wasn't gonna rap",'neutral'),
          ("I am Sebastian Artois",'neutral'),
          ("She'll be on cloud 9 after that chuffed for her",'neutral'),
          ("I think I will stream tonight",'neutral'),
          ("Fish, sweet potato mash and veg for lunch...i have my sister spoilt",'neutral'),
          ("Bon voyage to our @BBCCiN young carers who head off to #Dounans @SOEC_orguk for an activity packed week!",'neutral'),
          ("Closing track from the @ryan_vail  album, it's a soother! It's some album. Buy, stream, listen!",'neutral'),
          ("You really think they will turn nose up 2top wages",'neutral'),
          ("whoever else play's with them.",'neutral'),
          ("Kat Moon has shown off a new style in preparation for the Irish #EastEnders spin off…",'neutral'),
          ("Because why not",'neutral'),
          ("If you've received a new wooden egg shaker in your @Bookbug_SBT Toddler Bag, we'd love to hear your feedback...",'neutral'),
          ("Everyone say hello to Poppy, she arrived into @EDI_Airport this afternoon with @lufthansa from Larnaca.",'neutral'),
          ("We're giving away 5 delicious LINDOR Strawberries and Cream boxes, just RT to enter!",'neutral'),
          ("@richardajkeys you think his approach with zonal marking is confusing the players?",'neutral'),
          ("@strikergolfshow Got an Motocaddy S3 in stock, could order an S1 for you, would be here by Wednesday?",'neutral'),
          ("Why are there people playing Uno in the uni computer room?",'neutral'),
          ("Newsweek reports on Touring Westeros by bus in Northern Ireland",'neutral'),
          ("My #HomeopathyAwarenessWeek joke is performing strongly. No RTs keeping the dilution super high.",'neutral'),
          ("RT @MagimixUK: RT+FLLW to win a mighty Le Blender to create the ultimate soups &amp; smoothies. Terms:",'neutral'),
          ("@SkepticalHusky They can argue that you can watch extras on the player but why should we?",'neutral'),
          ("All I want is shredded chicken satay half and half with a tin of Fanta orange... or a packet of reeces chocolates and a tin of boost. Eughhh",'neutral'),
          ("RT @ChemistDirect: #win one out of five @DrBronner Rose Castile Liquid Soap bundle worth over £12 each! #RT and #follow to enter!",'neutral'),
          ("For the U21s tonight.",'neutral'),
          ("Now is the time for Cork TDs to lobby [for libraries]. We hear you Mr. Nevin Power in the @CorkEveningEcho #Cork",'neutral'),
          ("When you think you're ready for Monday",'neutral'),
          ("I'd imagine its unpaid so might suit newcomer looking to increase exposure",'neutral'),
          ("Can we be back in Newcastle @suzannelyon_",'neutral'),
          ("RT @Bakerdays: #Competition: #Win a Letterbox cake! Just Follow &amp; Retweet to enter!",'neutral'),
          ("I'm the type of person that will listen to a song I like approximately 400 times in a row and right now that song is work from home",'neutral'),
          ("@kateontheradio Natural Mindfulness walks will be available in your neck of the woods from May",'neutral'),
          ("@ThreeIreland  can you please tell me your customer service number for ireland is please",'neutral'),
          ("8 Digital Marketing Tips for New Business",'neutral'),
          ("Bra fitting experts from @lovepanache will be in store this Friday from 10.30am - 5pm.",'neutral'),
          ("Ready to hit the beach!! @ Croyde Bay Beach",'neutral'),
          ("Lots of highlighting &amp; research for @IncludeYouth new Meant to Work programme through @QueensLeaders",'neutral'),
          ("why would they? And is it?",'neutral'),
          ("Helloooa, its barbara's teddies here on profile. Barbara Naughton lost her British sim and it will be up and running in a few days.",'neutral'),
          ("Are they ever useful?",'neutral'),
          ("@keithdkennedy yeah what's with the snap code? ",'neutral'),
          ("Come on people. Do it now.",'neutral'),
          ("Early finish on a Monday",'neutral'),
          ("Just got the dates for #FirstDatesIRL &lt;--- and thats the hashtag are going with..",'neutral'),
          ("That's what I thought, why I asked",'neutral'),
          ("@maidai Had no access to Internet and only seen ur message now.. Rosie's relatives are like most in the world.",'neutral'),
          ("My heart goes out to you but... I don't care that much.",'neutral'),
          ("Spoiled for choice with the gigs coming up in Waterford",'neutral'),
          ("I am still so confused about what Suicide Squad is about.",'neutral'),
          ("@andrewastewart @vodafone surely you could raise with ofcom to get a permanent fix and some compensation?",'neutral'),
          ("@JFTAXI replying to @KZapponeTD about gender balance in INM",'neutral'),
          ("Giving 1st year law students big pep talks for their exams",'neutral'),
          ("Time to get 2nd year done and dusted.",'neutral'),
          ("See how many #dcfcfans have attended #dcfc matches",'neutral'),
          ("@peterbrownbarra because @BBCRadio4 is an England-only service, or else because its producers think 'England' and 'the UK' are synonymous.",'neutral'),
          ("I've started properly watching Catastrophe",'neutral'),
          ("@moonlighter1872 sent you a mail bro",'neutral'),
          ("sloths I think",'neutral'),
          ("@LaceyDermot Nobody in Labour HQ  has any idea. They wonder what you do.",'neutral'),
          ("song lived by my son my granddaughter and I.",'neutral'),
          ("That is usually what they do when the rug is lifted",'neutral'),
          ("Don't speak to soon Jonathan we just don't know what's coming next!",'neutral'),
          ("Someone please come order food so I'll have something to do! #bored #boredwork #tweetme",'neutral'),
          ("If the Orange One can't run a ground game &amp; can't learn the various state delegate rules",'neutral'),
          ("I spent it all on Dark Souls",'neutral'),
          ("just wanted to make sure your community knows about it",'neutral'),
          ("Has Megan or hasn't she slept with jake? Doing my head in not knowing.",'neutral'),
          ("The original demo is here:",'neutral'),
          ("Our Shearwater Hotel, Ballinasloe competition closes at 9pm tonight - re-tweet our pinned tweet #Galway #win",'neutral'),
          ("@maidai I haven't been in touch with her since the last day I commented back as i had so much to do.",'neutral'),
          ("Don't rush, don't pressure",'neutral'),
          ("@Dollarlogic Politicians change their mind all the time ,we pay them to do this and corporates try to think for them",'neutral'),
          ("@mmcuriee I had her for my last four years and by the last two the classes",'neutral'),
          ("In the last year we would have tea and biscuits",'neutral'),
          ("@VodafoneIreland can u call her  I can pm her number now.",'neutral'),
          ("We can protect your outbuildings and machinery",'neutral'),
          ("@LaceyDermot You may not protest but you are truly revolting.",'neutral'),
          ("@KMaj8 I just need to get you *just* the right level of drunk, basically...",'neutral'),
          ("@dwphousing We've got a few more spaces left in our summer beta, have you seen it yet?",'neutral'),
          ("@cb_no3 aye I thought 10 plus an extra 7 but tbh I'm no really sure",'neutral'),
          ("New record at Narita airport as a result of bad preparation:",'neutral'),
          ("Arrival at airport by train 21:10.",'neutral'),
          ("Taking seat in airplane 21:25.",'neutral'),
          ("@xsarahl_x Sorry a bit late with these &amp; some r kinda blurry but here's 4 of 5 pics I got of u at de airport",'neutral'),
          ("@JFTAXI Dobbo made a joke bout having to declare an interest in the university.",'neutral'),
          ("So I asked him if he had any other interests to declare",'neutral'),
          ("Wouldn't that be in keeping with their policy",'neutral'),
          ("Just asking",'neutral'),
          ("You can't scream, but you can be ratchet.",'neutral'),
          ("@e_man @wesfrdrk if Goff or lynch are there they'll go QB",'neutral'),
          ("@XboxSupport Hi. I'm encountering unusual issues online atm. My network and multtiplayer connections are fine but I cant connect to Xbox...",'neutral')]