tweets = [("omg its already 7:30 :O",'positive'),
          ("Juuuuuuuuuuuuuuuuussssst Chillin!!",'positive'),
          ("handed in my uniform today . i miss you already",'positive'),
          ("hmmmm.... i wonder how she my number @-)",'positive'),
          ("thanks to all the haters up in my face all day! 112-102",'positive'),
          ("Feeling strangely fine. Now I'm gonna go listen to some Semisonic to celebrate",'positive'),
          ("You're the only one who can see this cause no one else is following me this is for you because you're pretty awesome",'positive'),
          ("goodbye exams, HELLO ALCOHOL TONIGHT",'positive'),
          ("uploading pictures on friendster",'positive'),
          ("(: !!!!!! - so i wrote something last week. and i got a call from someone in the new york office...",'positive'),
          ("... Do I need to even say it?  Do I?  Well, here I go anyways:  CHRIS CORNELL IN CHICAGO!  ... TONIGHT!",'positive'),
          ("... health class (what a joke!)",'positive'),
          ("bathroom is clean..... now on to more enjoyable tasks......",'positive'),
          ("boom boom pow",'positive'),
          ("go give ur mom a hug right now.",'positive'),
          ("Going To See Harry Sunday Happiness",'positive'),
          ("I always get what I want",'positive'),
          ("I bend backwards",'positive'),
          ("i get off work sooooon! i miss cody booo. haven't seen him in foreverr!",'positive'),
          ("I'm really going to bed now...",'positive'),
          ("Jin has a twitter.",'positive'),
          ("just gonna smile...cuz it is what it is..and im not sure what more they could want..",'positive'),
          ("Just got home, and I got to see my friend Zahra whom I haven't seen since We graduated!!!  That makes me so happy.",'positive'),
          ("oh thank you!",'positive'),
          ("pleased", 'positive'),
          ("Rose and ood will be back in the Xmas Who special!  YAY!  Damn that's half a year away.",'positive'),
          ("Thanks, I need all the help i can get.",'positive'),
          ("that explains alot.",'positive'),
          ("There's going to be a Heathers sequel.  Winona4ever!  They better not fuck it up.",'positive'),
          ("trae is so sweet! He just bought me a new baithing suit!! Wove him ",'positive'),
          ("True, highly subjective of me there. Tombre was actually my favorite character in the book. You got me",'positive'),
          ("sigh You cant love someone that doesn't love you back that's like stalker status . GET a divorce",'positive'),
          ("Aiqht Goodniqht . Tri, Neena, Malcolm, Chaise , JLew, ATL Love Much .",'positive'),
          ("Triiiiiii .  ily . even if Chaise doesn't . =D dies of laughter",'positive'),
          ("hot choco is the best!",'positive'),
          (":-D ))))))))...WHAT AN AMAZING NIGHT,DAY NIGHT AGAIN!! HI TWITS! I MiSS U GUYS",'positive'),
          ("enjoy chicago..b new venue is always cool. You shine everywhere you go. I know who you are. In time so will everyone.",'positive'),
          ("makes me smile.",'positive'),
          ("My first day off in 3 weeks, and my child got up before 7:00. So watch for me on &quot;Nancy Grac..",'positive'),
          ("I am happy you are staying around here. Drexel is a fabulous university. You should be proud. yeah.",'positive'),
          ("you want to start the morning later; in New York we can do that  (Californians have it even better)",'positive'),
          ("tell i said Happy BDay!!",'positive'),
          ("told you, you would sweep haha :-p",'positive'),
          ("The servers are now backup, if you experience any more problems then please let me know  Sorry about the delay...",'positive'),
          ("yes, i am lol j/k luv this! you are like a gentle breeze that has blown through...",'positive'),
          ("awesome",'positive'),
          ("pick up some flowers for the teacher I'm jealous! I want flowers without having to be in the hospital to get them!",'positive'),
          ("Thanks K! Here's hoping! Pretty nervous though...",'positive'),
          ("so do you give him every inch of your love every night?",'positive'),
          ("Maybe you can pop a tweet. They are quite active on twitter.",'positive'),
          ("What's up? Hey you! I'm doing ok, thx. You? You, too! TTYL! Oh, sorry! lol",'positive'),
          ("Thanks for letting me know. I'm going to check out Eureka later with this knowledge",'positive'),
          ("HAPPY MOTHERS DAY!",'positive'),
          ("raybooysen I knew Sharepoint was written by interns, I just knew it !!",'positive'),
          ("I am happy",'positive'),
          ("haha omg. stayin steezy mowin the lawn... loviie still here goiing tanning soon.",'positive'),
          ("i wanna play with my camera but i will settle for playing with iv's and heart monitors",'positive'),
          ("lol all these robot pickup lines are hilarious",'positive'),
          ("my friends can get with ur friends and we can all b friends, shit, we could do this every weeknd.. Aiigght?  with coop n the crew",'positive'),
          ("such a beautiful satisfying day of bargain shopping. loves it.",'positive'),
          ("thank god today is friday !!! I love Ti Ti!",'positive'),
          ("thrilled about being at work this morning",'positive'),
          ("we break dance not hearts by Short Stack is my ringtone.... i LOVE that song!!!.....",'positive'),
          ("my life is very lazzzzyyyy!!!!!!!",'positive'),
          ("ish in a good mood .....tlk to me",'positive'),
          ("J + A MADE NiCE..... TWiCE! for now ;]",'positive'),
          ("loves life atm!   its brilliant XD",'positive'),
          ("who else is in a happy mood?? =D",'positive'),
          ("BYE EVERYONE!",'positive'),
          ("SO FAR SO GOOD!",'positive'),
          ("TODAY WAS A GREAT DAY!!!",'positive'),
          ("yippeeeee yay lets gather in the hay...HIS LOVE FOUND IT'S WAY+ boy,it's Gonna STAY added 2 the Master's HOLY WAY: ALL HIS WILL+WAY",'positive'),
          ("thanks for being the bestttttttttttttttttttt J-dawg",'positive'),
          ("praise God for this beautiful day!!!",'positive'),
          ("I love you guyssss! Those rings.. Mmmyeahh! Bling blingg",'positive'),
          ("Thank you very much for the DVD suggestion!  Very nice of you!  Looks good.",'positive'),
          ("had a WONDERFUL day  G_D is GRRRRRRRRREAT!!!!!",'positive'),
          ("I have passed 70-542 exam today",'positive'),
          ("I want to write a song. I think I will.",'positive'),
          ("you tease, i wanna hear the tracks!!",'positive'),
          ("Creativity via Twitter",'positive'),
          ("15 TravelTips 4 student safety in rough places",'positive'),
          ("Im sure he'd love that LOL",'positive'),
          ("What happened to movies, anyway? It's like Hollywood forgot: in rough times, the public wants to see..",'positive'),
          ("whoops credit is due to",'positive'),
          ("A blessed sunday everyone!",'positive'),
          ("dog riding the bicycle",'positive'),
          ("A problem shared is a buck passed",'positive'),
          ("am quite tired can't wait till wwe at burswood",'positive'),
          ("awake, and ready for the day",'positive'),
          ("Being NASTY in the studio with my woman!!!  Go SLEEPIES!!!",'positive'),
          ("feeling ok for the first time in a few days. thank you!",'positive'),
          ("found a new way to text him, yey!",'positive'),
          ("Good Nite.  I hope Grandma visits my dreams again tonight.  Last Night was uplifting...  I miss her.",'positive'),
          ("Goodbassplayer... that is funny.... ;)  OilIPO.... I hope the people that will bring us good things are started early this week...",'positive'),
          ("I'm here to tell ya ... very yummy.  Decided to go on a hunt for blender drinks ... know any good ones?",'positive'),
          ("is listenin to my new fav band more amor",'positive'),
          ("Just another day in paradise. ;)",'positive'),
          ("love you!",'positive'),
          ("about to pop in a movie chill a bit... get it innnnn.! call n text",'positive'),
          ("about to swim",'positive'),
          ("ahhh. Drizzy. Mr. Rogers, you are indeed the best.",'positive'),
          ("All the small things...",'positive'),
          ("always a nice thing to wake up to. yay. :p (gosh I'm such a typical lame overanalyzing teenager) lmao  / had a nice nap.",'positive'),
          ("am excited",'positive'),
          ("Am feelin very happy!? ",'positive'),
          ("Another Friday night of Rock Band",'positive'),
          (": D a million making a difference. I can't help but to believe. I came in believing &amp; I will leave believing GOD IS!",'positive'),
          ("Good morning all! Have a great day!!!",'positive'),
          ("having a luvly day",'positive'),
          ("he is so hot !",'positive'),
          ("Iowa No. 2 in happy! Yea!",'positive'),
          ("just got home",'positive'),
          ("just saw sink into me the whole video on kerrang! ive seen it before loads but its so much better on tv!",'positive'),
          ("My mom is the funniest person ever! ",'positive'),
          ("Pie seems to have quite a good appetite now.",'positive'),
          ("she is amazing -- Bjork Bachelorette",'positive'),
          ("Thank you.",'positive'),
          ("this pic If u want more tell me cause I got more",'positive'),
          ("Im in love and I don't care who knows it -elf",'positive'),
          ("as simple as it gets.",'positive'),
          ("at my tweets: 1 lady saying goodnite, 2 tweets later 1 lady is saying good morning - that's crazy - i would never imagined this yrs ago",'positive'),
          ("at the nursery. the wailing have just ended. all sleeping soundly. working morning shift tmrw. grr",'positive'),
          ("AT THE RANDOM MENTION ABOUT CORE 2 DEALS THAT ARE ALMOST TWICE AS MUCH SENSE AS IT'S NOT TIED TO HIMSELF ABOUT TV EVERY NIGHT.",'positive'),
          ("awake...finally..random dream...i was a penguin but i lived in jersey and i oddly lived in a icecream store lolz",'positive'),
          ("awesome black coffee... anyone?",'positive'),
          ("aww great song Picture to burn",'positive'),
          ("baby sitting today.. shopping tomorrow.. Rue 21 Is the best Ever..",'positive'),
          ("baby you like my favorite dessert I just can not get enough of you love you I'm yours 4Eva",'positive'),
          ("BAHAHAHA  me and jodie burst out doing kevin's sos dance!  EPICCC XD",'positive'),
          ("been up for 2 days straight. LoL. i NEVER sleep.",'positive'),
          ("the weather is good!",'positive'),
          ("third date went well....moving on to fourth!!!!!!",'positive'),
          ("To The Death! An awesome random comic for the certifiably not sane.",'positive'),
          ("two more days.",'positive'),
          ("yay for STAR testing week! I start school at 11am this week and I have no school on thursday! maybe SF...",'positive'),
          ("Hello World! This is where i live: beautiful 5am woop - bed now",'positive'),
          ("that's me smiling.",'positive'),
          ("The universe is a living being, and it's conscious, and it's very old. And it cares about itself in lots of ways. Drunvalo Melchizedek.",'positive'),
          ("the world makes music for people who listen",'positive'),
          ("exited I just bought some oreos!! I hope everyone likes oreos..",'positive'),
          ("BABBBBBBBBYY .  I missed you MUCH!!",'positive'),
          ("finally got twitter haha",'positive'),
          ("I think there may be a connection between Paul Reubens and the reason why movie theater fl..",'positive'),
          ("temperature is down, but the pain is still bad. Hoping antibiotics kick in soon! Thanks for asking",'positive'),
          ("said I tweets less these days so, hi!",'positive'),
          ("Would love to see you guys sometime! grin - and aw rats, maybe it'll warm up real fast??? LOL",'positive'),
          ("Seeing a guy dressed up as a banana totally made my day. Phallic symbol FTW",'positive'),
          ("=D There's my BOO.  Blushes",'positive'),
          ("You aint gotta apologize. I know I'm not ugly.",'positive'),
          (";) Butterfly Day (Jun 19, 2009) Holiday",'positive'),
          ("work.. || Only 5 hours of it today and then weeeekend!  Can't wait for the long weekend to begin! Gonna get some things done for sure!",'positive'),
          ("Praying for my cold to go to my head because a skunk just sprayed my yard. This is the w..",'positive'),
          ("Created from the realms of Light, pure love commands the fold When you think and speak with love, a new world you'll behold~",'positive'),
          ("Yes, before the show, I suggested that we ought to do a celebrity deathmatch",'positive'),
          ("Dear hyper chihuahua, we only have 45 minutes left together on this drive, but I have a ..",'positive'),
          ("looking fwd to a twitpic of selma soon. Cool name, add a k to the end and it's tok'ra",'positive'),
          ("yea I really wanna see a win for him at daytona",'positive'),
          ("aww I'm sorry bae u kno I be grindin =D BUT I GOT U I SWEAR....I needa go buy an artbook that or construction paper",'positive'),
          ("thanx for the post the warm wishes.. enjoy ur day!",'positive'),
          ("you are the best!!",'positive'),
          ("my car is best",'positive'),
          ("Good Morn,happy birthday !  regardless of what ppl said yesterday,they don't realize what happend behind the scene.",'positive'),
          ("getting a webcam today.",'positive'),
          ("getting ready to watch the Sprint Cup boys try to tame the concrete Monster Mile! hopefully tires won't be too much of an issue! ",'positive'),
          ("go follow my personal twitter!",'positive'),
          ("Go Wings! FTW!",'positive'),
          ("God i'm up early. Hayley still asleep but today is party day so i'm getting stuff ready.",'positive'),
          ("going home to see my baby   [dont be ashamed of your faith]",'positive'),
          ("going out for dinner with the family ",'positive'),
          ("going to bed.",'positive'),
          ("Going to London Expo this weekend  Can't wait !",'positive'),
          ("goingg to sleep  school , then out for pizzaa!",'positive'),
          ("Gonna WoW for a bit. Later, Twitter",'positive'),
          ("good morning lovely!",'positive'),
          ("good morning/afternoon. Things will be great today.",'positive'),
          ("Online reality blogging tweets... My Life On the Social Media D-List",'positive'),
          ("ooh, but Clean Sheet Day is awesome!! Woo!  hope you're feeling better now?",'positive'),
          ("I think I've won the battle over the impending crud. Enjoy your drive this AM",'positive'),
          ("Crickey can't think that far ahead - think getting to 2009 followers is pretty ambitious ",'positive'),
          ("Coffee keeps me running. In fact, without coffee, I wouldn't get any exercise at all",'positive'),
          ("I bookmarked it and will check it out after I get some sleep. Thanks Sam!",'positive'),
          ("ur hot",'positive'),
          ("has Briso on DVD.  I haven't seen it all yet but I enjoy it. I saw Army of Darkness and Evil Dead because of Hubs too.",'positive'),
          ("What a considerate Tooth Fairy you are, checking to make sure you didn't miss anyone.",'positive'),
          ("We are perfectly on schedule' - Nobody is waisting time today  (Don't mention the Sun again;) Dedicated audience",'positive'),
          ("My twenties: Look, a bed! WONDER WHAT WE CAN DO. My thirties: Look, a be--ZZZZZZZZZZZzz",'positive'),
          ("If it weren't for unspeakable things, I don't know what I'd do.",'positive'),
          ("i've been ok just got through crying with leah frowns at the thought we were talking about our dead fathers",'positive'),
          ("cooking!!!",'positive'),
          ("100 followers!  YAY!",'positive'),
          ("1 follower WOW!",'positive'),
          ("makee a wishhh ;) GOODNIGHT",'positive'),
          ("I know what I'm wishing for!",'positive'),
          ("155 days until the JB'concert in Milan!!!!I'm guarding my tickets",'positive'),
          ("30 lbs lost since Feb. Still have a lot more to go.",'positive'),
          ("Good Night ! Okay, I got really nothing to say.",'positive'),
          ("Good night! Arrgghhhh 5-2 B.P. Do work boys!",'positive'),
          ("good to hear from you",'positive'),
          ("good weekend",'positive'),
          ("goodnight  ! spanish finals tomorrow. spanish should be easy. woo.",'positive'),
          ("gooooood morning my twitter friends!  Have a nice sunday",'positive'),
          ("Gossip girl tonight!!!",'positive'),
          ("Got Escala's new album now.  T'is very good ",'positive'),
          ("Got new photoshop magazine but I need my Dad's portable CD drive to use the CD with the pics on it D: I think I'm stuck there tomorrow",'positive'),
          ("gotta love her. glad she had fun. looking forward to the beach w/ her!",'positive'),
          ("Great day people-watching in Berkeley with my bro  I love him.",'positive'),
          ("great nite",'positive'),
          ("Great tights, good outfit!",'positive'),
          ("had a good night, love my best buds in the world!!!",'positive'),
          ("had a Really good night!!! Stoked for things to come!!!",'positive'),
          ("had an ok day. it went by fast.",'positive'),
          ("hah! that was awesome. just listened to you. pretty cool!  i love for crying out loud.",'positive'),
          ("haha I really did and I'm about to call music unlimited tomorrow for  Simon..tryin to be like ROD ;)",'positive'),
          ("63/100 for my MSC120 Assignment that was incomplete!!!! Relief",'positive'),
          ("actually I might be crazy 'cause I love my job.",'positive'),
          ("actually quite happy toady. apart from the agony all over my body, and not being able to go outside :L done some revising so all's gd",'positive'),
          ("ah belhblehbleh the familys watching a movie and yes imm being a computer nerd :p and i wish jerkface would wake up onee daaayyyy!!!!",'positive'),
          ("and Is there a waiting line to get into Club Blip? ;)",'positive'),
          ("and I dunno why but with you I'd dance in a storm in my best dress.",'positive'),
          ("5 days to the musical  i'm gonna dance wow WOW wow it's gonna be something like High School Musical ihihih xoxo Petia",'positive'),
          ("a goodmorning back at chat",'positive'),
          ("a perfect weekend",'positive'),
          ("a pony's clop-clopping down the hill (heard him long before i saw him). this would so not happen in Brooklyn barring a cop on horseback.",'positive'),
          ("all done., time to finally start shuting down",'positive'),
          ("all smiles. im fairly hapy with what has happened yesterday, even though some other had to put a damper  on things",'positive'),
          ("almost done wit the painting tired as crap. Sleep time. in love with u - ziggy marley and erykah badu",'positive'),
          ("also made a masterful roast dinner, followed by apple crumble! .. Yum need gym this week though!",'positive'),
          ("am 200 updates in Twitter",'positive'),
          ("am i too immature for a 16 year old? I just really like Ninja ponies..that have only 3 legs.",'positive'),
          ("Hanging out with Steven Mohler on Sunday! ah :]",'positive'),
          ("happy birthday to me and mom! Why am i always the first one up? So here i am falling off the bed cuz someone is a bed hog",'positive'),
          ("happy face.",'positive'),
          ("happy that its sunny",'positive'),
          ("happy that it's sunny",'positive'),
          ("happy to see him",'positive'),
          ("happy with the way thing are going",''),
          ("Happy, knowing my friends are still my friends.",'positive'),
          ("happy. spending time with mum",'positive'),
          ("Has Just Got Up Is Listening To Good Charlotte",'positive'),
          ("has something very special in mind",'positive'),
          ("have a nice day... cause i will!",'positive'),
          ("haven't updated in forever",'positive'),
          ("Healthy Butcher, exclusive cheese, sexy bread, lovely beer, some super sparkly wine Apple fucking Tango are all inside my belly",'positive'),
          ("Heard it on Pandora because that site is THAT cool",'positive'),
          ("hee hee. your so weird. and i did NOT shiver.",'positive'),
          ("Hey Terri! The game isn't too expensive, but over time, you'll have made quite an investment...",'positive'),
          ("hey...i'm back..if someone want to talk.. here i am.",'positive'),
          ("Home finally.Making fettuccine and relaxing my sore feetsies!",'positive'),
          ("Home sweet home (: finally back XD",'positive'),
          ("homeish lol..hella fun day  .. Thanks leela thai  .. Thanks paul.. Thanks michelle mufid Cristina kittykat  .. Awkward moose ?",'positive'),
          ("any comment on the latest star trek movie? is it nice?",'positive'),
          ("any day now, any way now. I Shall Be Released.",'positive'),
          ("Are you going to be taking photographs tonight??? :O",'positive'),
          ("ARRRRRRGGGH!   I cant wait till next weeeeeeeeek!",'positive'),
          ("AT LAST!! Successful deployment complete.  Soo.....what do I do now?",'positive'),
          ("At work.. having a postive attitude!!",'positive'),
          ("awesome day! soooooooooooooo happy",'positive'),
          ("awesome! Man, I miss you. I woke up thinking about you....it looks like you've been in my dreams!",'positive'),
          ("aww dont make me blush!",'positive'),
          ("Baby strampelt fast im Takt (New Soul - Yael Naim)",'positive'),
          ("back here, I was busy xD Wirting Stars Loves, almos 400 pages xD and listenint AFH and TV",'positive'),
          ("hope you all are having a good day/night.............. :-D",'positive'),
          ("i agree",'positive'),
          ("i am back",'positive'),
          ("I am falling in love with Stockington - such a witty wise meow meow!! ^^",'positive'),
          ("i am musical today!",'positive'),
          ("i am very happy today! and i don't why? ",'positive'),
          ("i beat you video on youtube",'positive'),
          ("i can't wait to go home and watch danny phantom! While talking to stephen",'positive'),
          ("I can't wait to go to Las Vegas! 20 more days! OMG!",'positive'),
          ("I Cant wait to watch britians got talent !!!!!! I dont like holly :O",'positive'),
          ("amazing people",'positive'),
          ("An online number lets family and friends call you at local rates wherever you are in the world. Loving Skype",'positive'),
          ("Anyone else on Dropshots? My id is katjrobertson  It's password protected tho, so u'll have 2 ask me.",'positive'),
          ("Arizona Real Estate Specialist - View ALL HOMES for sale in arizona on my website FREE",'positive'),
          ("At a cabaret with my family; I love them!! .. In my comfort zone",'positive'),
          ("at home eating mcdonalds cinnamelts a oreo frosty.",'positive'),
          ("at my grandmas eating good.",'positive'),
          ("at the manila right now.",'positive'),
          ("back from shower.",'positive'),
          ("back to hotel. time to start work ",'positive'),
          ("BBL ppl ~ have to go to school~",'positive'),
          ("boring.. wait! i will comment on my friend in FS first!",'positive'),
          ("bout to party in a tent",'positive'),
          ("Brokeback Mountain'is so beautiful, and so amazing, and so freaking sad.",'positive'),
          ("brooklyn bridge for the first time ever. yay life =D",'positive'),
          ("But caught Bullet Boys, Trixter (Pete was great), LA Guns AND Kix (who stole the show). Hung out backstage like a real rock and roller.",'positive'),
          ("I finally have updated from a computer. THANK YOU DAD",'positive'),
          ("Be careful... white at a BBQ is a high risk. But the dress is really awesome!",'positive'),
          ("Beautiful day here on StT. Bout to head to Magens Bay- soak up some sun. Loove Saturdayss.",'positive'),
          ("Beboing, Twitteringinging, TVing!  dihd i say i luv twilight yet? Wel... I LUV TWILIGHT!",'positive'),
          ("camp in confirming that he will be in San Diego this fall for the PRSSA Convention. haha.",'positive'),
          ("Can See clearly now the rain is gone. ",'positive'),
          ("can't stop smiling after talking to him all day...  ...Why couldn't I have met him months ago?!?",'positive'),
          ("Cant waiit! xxx.",'positive'),
          ("can't wait 'til wednesday!!!! CHAMPSSSS!!!!",'positive'),
          ("can't wait to get my share of her check today. Lol",'positive'),
          ("chillin!!!!",'positive'),
          ("Chinese for dinner and working on a cool website template. So proud of myself.",'positive'),
          ("choppin it up w/ i love you",'positive'),
          ("concert later tonight!",'positive'),
          ("i have a buzz",'positive'),
          ("I have finally seen Clerks, from beginning to end and no TV swear-word editing (poor Jay! xD). I feel somehow fulfilled.",'positive'),
          ("I hope you find a great trousers",'positive'),
          ("@orlagartland just got tickets to  Limerick gig for the Bry tour!Hope you do cover of book of love &amp; hold back...! Love Roots EP!",'positive'),
          ("@Nadya130993 thank you",'positive'),
          ("@PeaChambers @PSAAcademies @PSaintAndre awesome day and great to have you both there, he's got some skills! Hopefully see him in the summer!",'positive'),
          ("mummy has told me how luvly it is!",'positive'),
          ("Great morning light in the Outer Hebrides",'positive'),
          ("Had the BEST couple of days with this lot and all the others for @zoemelissa2 's birthday!!…",'positive'),
          ("@Conjob123 @leeoxS6 yeah rose is bolloxed, could do with Cabrera having a good back nine and sneak into the places",'positive'),
          ("@BeattieDoug @SteekieNolan Was always a safe bet that Seamy had a small willy",'positive'),
          ("but I like playing around with dark chocolate and whiskey too!",'positive'),
          ("can't wait xox",'positive'),
          ("Turned over to @BBCTheVoiceUK and Codys singing Imagine!! All i can think of is singing this with @YOUNGAMERICANS",'positive'),
          ("Ally McC is a Rangers legend .. NEVER FORGET THAT .. As a manager he worked with a Board who raped Us .. never forget that .. Legend",'positive'),
          ("@CampbelliansHC well done guys",'positive'),
          ("People are going to judge you no matter what you do. So forget everyone and be yourself.",'positive'),
          ("@TomBoxingAsylum he blows the midget out in a few rounds",'positive'),
          ("Is there a reason why #kevin is dressed like a bag lady on #TheVoiceUK ?  Good job @stephenfry not on twitter!",'positive'),
          ("@thatweecafe @DrewMcMenamin your salad secrets are safe with me",'positive'),
          ("Having an @adamkmccarthy sized piece of beef for dinner tonight.",'positive'),
          ("People are so judgey and I'm just here like 'yaaasss wear those booty shorts and go get you some dick gurl' lmao",'positive'),
          ("@th0t_control @NazdravIje And you, Bud.  :-)",'positive'),
          ("Another year, another victory over Plunketts. Great to get our first win of the season heading…",'positive'),
          ("An action-packed day and a winner in the Aintree Grand National...picked by my 4 year-old nephew! #RuleTheWorld",'positive'),
          ("Next #CottonMalone #book by @SteveBerryBooks is finally out. Hello sleepless nights #reading",'positive'),
          ("@Nadya130993 louis please",'positive'),
          ("You can't deny the tenuous, tenuous humour",'positive'),
          ("Love the venue! Jaysus :)",'positive'),
          ("Well done @robertdunne15 finishing 3rd in #GrandNational today @AintreeRaces",'positive'),
          ("And they're off! Thank god for BBC coverage #Masters2016 #gameon",'positive'),
          ("I for one would love to see Ally back at Ibrox celebrating our return .. He Played his part",'positive'),
          ("Wooooohoooooo back on the beers at last!  Way too much fun with the MSQRD",'positive'),
          ("Nice wee mention in The Irish Times for The Exile EP...",'positive'),
          ("@PBNPPhotography Thank you.",'positive'),
          ("Printed off my #photo of #lahinch from last weekend, one for the wall! #clare",'positive'),
          ("#thevoiceukFINAL Ricky&amp;Kevin loved that !",'positive'),
          ("@FollowsLove @aya_jordi @Nadya130993 louis will miss  me",'positive'),
          ("@Phizzfest Cannot Wait for this!!!!",'positive'),
          ("Fun has begun",'positive'),
          ("@BBCTheVoiceUK @Kevsimmx @Rickontour that was brilliant... Loved the vibe.",'positive'),
          ("Tomorrow will be the first time in over seven months I'll be involved in a matchday squad. Not expecting to play but I'm v happy to be back.",'positive'),
          ("This is the life. Relaxing by a roaring fire in the beautiful Irish countryside #Ireland #fire…",'positive'),
          ("@Sylvana0902  at least I'm not the only one thinking this?!",'positive'),
          ("@JohnDolanSeanad @Sabina_Brennan @IMFNews “Children are innocent &amp; love",'positive'),
          ("justice, while most adults are wicked &amp; prefer mercy. GK Chesterton",'positive'),
          ("Brian Gartland has scored Dundalk's 1000th Premier Division goal",'positive'),
          ("@rfc_david Safe trip Tam, hope the Battle Fever is on!",'positive'),
          ("I always preferred a comedy anyway #NUFC #BPL",'positive'),
          ("#BritainsGotTalent paisley kickass!",'positive'),
          ("Happy birthday Seve @ Augusta Drive, Maryborough Woods",'positive'),
          ("The Rye aka 'the best band in the world' starting at 10.30 tonight @dockno1 #dontbesquare",'positive'),
          ("Fife was glorious today #scotland #gorse #sunshine #spring @ Largo Law",'positive'),
          ("Actually praying that the weather will be nice tomorrow",'positive'),
          ("Done! @vanderbellen for President!",'positive'),
          ("#kenonthecourse the lump of hay just made that... Beats the skycart any day",'positive'),
          ("@Rickontour has another class act in @Kevsimmx The fact that they have just sang my jam has me won over #TeamRicky #bbcthevoiceuk",'positive'),
          ("Return of the Jedi with the kids. All kinds of awesome!",'positive'),
          ("Sometimes Ireland out does itself!! Tommy Craggs' wildlife carving at St Anne's Park! #LaceyTour…",'positive'),
          ("@farmermartin16 aye you will have tear in your eye when baby M arrives, all the best to you both.",'positive'),
          ("This really is a case of the least worst team going to the playoffs #RedWings #Bruins #ReverseGear",'positive'),
          ("I was kinda panicking today. But now I'm fine. Thanks very much to @trisharooney @ciaran82 and @nbrez for keeping me calm!",'positive'),
          ("Has to be said #Power (now on Netflix) is better than #Empire Much better script and decent acting (except @50cent who can't act)",'positive'),
          ("@AndyTCarroll well done lad. That must have felt good? #whufclegend",'positive'),
          ("@_Inno Very sorry to see the news about your Mum, thinking of you and your family x",'positive'),
          ("@marshmallowylu attempted arson is a good conversation starter with flat mates",'positive'),
          ("The only thing for it - thank you @CrabbiesUK @Channel4Racing for a brilliant race, will miss you #GrandNational",'positive'),
          ("No such problem when it was used with Windows 7.",'positive'),
          ("Good work guys.",'positive'),
          ("I feel like group/squad photos would look so much better if we were all the same height",'positive'),
          ("You must never need to go to the gym",'positive'),
          ("Again, in reference to the strenuous nature of my work and how they reckon this keeps me fit.",'positive'),
          ("@Bev_See @MissRhiaDee 1st half were desperate for United but did say we were playing well I suppose",'positive'),
          ("How can it be possible a child of 12 can sing like that? I hate that bloody song but, wow! #BGT",'positive'),
          ("And here is #ifta winning @MoeDunford #talkingvikings",'positive'),
          ("@paaijj freeking savage af",'positive'),
          ("lol I was so excited I didn't @ Hetty soz m8 xx @Hisnotonfire",'positive'),
          ("@EthanFitzy nice one thanks!",'positive'),
          ("#vinb @rte @DailyPlato Thank U and Prof. Sona Datta (@  BBC 4 ) for the wonderful accounta of the Treasures of the Indus. Spectacular!",'positive'),
          ("@NazdravIje @th0t_control I suppose you're not so bad, either. :-)",'positive'),
          ("@Square_Mealz Best Of Luck",'positive'),
          ("this 12 year girl on #BritainsGotTalent ...what a voice....wow",'positive'),
          ("Was not expecting that massive voice to come out of that wee girl #BGT",'positive'),
          ("@CleaverGavin @SBIdotcom @lorrainecleaver Your'll be pleased to know I picked it out the hat for you at work",'positive'),
          ("Just about to see #Starman by @tumblecircus in the @NatOperaHouse #wexfordhour #excited",'positive'),
          ("Congrats on the IFTA @AilbheF #anklondike #tg4 #abumedia #ifta16",'positive'),
          ("@UrbanCityCowboy @W_Autism_Comm Yes sorry ran out of characters :) SS = Social",'positive'),
          ("Defying Gravity is one of the best songs on Broadway though I don't think anyone has done it better than Idina Menzel #BGT",'positive'),
          ("liam looks so good i am weeping",'positive'),
          ("Just returned from a wonderful trip to the city centre, Dublin (@ Landsdowne Valley Park in Dublin)",'positive'),
          ("@vegetarijenn thank you!!",'positive'),
          ("@BryOnTour love it!",'positive'),
          ("Holy crap!!!! :O #BGT #BritainsGotTalent",'positive'),
          ("she's got a really amazing voice omg she's only 12",'positive'),
          ("@BigB0bbyT Yes, very good call.",'positive'),
          ("@DaffysGin were gonna take you to venice, rome, Tuscany and Florence :)",'positive'),
          ("HES SO CUTE",'positive'),
          ("R. Kelly said it best.",'positive'),
          ("Wind 3.6 km/h NNE. Gusting 16.1. Barometer 998.21 hPa, Rising. Temp: 5.5C. Rain today 1.6 mm. Humidity 78%  #weather #connemara",'positive'),
          ("A female cat was lost on 23/01/2016 in College Road, #Cork",'positive'),
          ("A cheeky race day collection 2013-2016 never failed to impress! #4thYearBlues",'positive'),
          ("Wow that little girl is incredible!!!!! #BGT",'positive'),
          ("What is it with Ayew and scoring really good consolation goals",'positive'),
          ("I have actual goosebumps #defyingGravity #bgt",'positive'),
          ("@karenspics18  hey babe nice picture x",'positive'),
          ("@tinusleroux eish, don't I know it. Come September :)",'positive'),
          ("#classichits4fm party followed by the after party = great night but sore heads!!",'positive'),
          ("@WanderWithJo omg yes!!!!!!",'positive'),
          ("YES PLEASE!!! :-))))",'positive'),
          ("@BoyneBrewhouse @CopperSpices looking forward to seeing you all",'positive'),
          ("@thefourthcraw @EilidhPinkChic gawd help him, now he has us 4 clingers on now too! #bigpeopleandlittles",'positive'),
          ("@jackllukeman Larry O'Rourke is a friend of mine at ESA whose job is to drive the Rosetta satellite around comet, lots more Science on way!",'positive'),
          ("i feel complete",'positive'),
          ("#BGT this girl is amazing?! She's literally singing one of the hardest songs to sing in musical theatre and she's TWELVE",'positive'),
          ("@jonnyfallon Someone said on the radio today that if you want to live long, marry a clever woman. :-)",'positive'),
          ("Thank you @LincsSkies @WestLindseyDC @LincsLife @LincsPrideMag - do miss #mountains in Lincs but there are some big #skies ..",'positive'),
          ("In tmrw's paper: Suzanne Breen says Michaella McCollum lied and bleated...but her future is rosy.",'positive'),
          ("Hello @Udacity ! Welcome to Europe. Check out",'positive'),
          ("Love it, just love it.... bring on whoever..... wins breed confidence ! Ask the pens ! #NYR #LGR",'positive'),
          ("Hands down the greatest day of his life #elephants #zoo #heaven @ Noah's Ark Zoo Farm",'positive'),
          ("@amyhuberman Showed Off Her Best Look Yet at Tonight's #IFTAS We're OBSESSED with that dress",'positive'),
          ("Give it 10 years and Disney will be casting this girl as one of their princesses #BritainsGotTalent",'positive'),
          ("You and I are gonna live forever",'positive'),
          ("#bgt #goldbutton  #wearestv #defyingGravity outstanding!",'positive'),
          ("@KP24 well played mate.",'positive'),
          ("Wow she was amazing! #BritainsGotTalent",'positive'),
          ("@zandraxsx @BBCTheVoiceUK looking very dapper Mr willson.",'positive'),
          ("thrilled! Thanks AM",'positive'),
          ("can't wait to meet this year's stars",'positive'),
          ("This girl on #bgt oh my god",'positive'),
          ("@ToyotaGB I quite like the fourth-generation Prius. When do I start seeing them in the streets of Leicester? I think it's the best one yet.",'positive'),
          ("Ok another level reached @iamwill &amp; Lydia wow #thevoiceukFINAL",'positive'),
          ("@MisssPatrice she was amazing. Get your money on her to win! #BGT",'positive'),
          ("That girl got me crying #wicked #bgt",'positive'),
          ("@marktaylor2709 My Greatest pleasure was telling friends to bet on this kid to win Majors .. They all did and won big money..  @McIlroyRory",'positive'),
          ("@lolIirot but you never have and that's what I don't get, you're basically embracing their culture n I don't see what's wrong w that",'positive'),
          ("That kid has more talent in her tooth fillings than Amanda Holden could ever dream of having  #BGT",'positive'),
          ("We were getting along famously",'positive'),
          ("Be creative and collaborate. @gmunk loves how technology connects us #OffsetDUB",'positive'),
          ("@AdamClarkers They'll leave, but I still think with some good recruitment we could do well next season",'positive'),
          ("@louclarkeradio Crazy! Hope no one is badly injured",'positive'),
          ("Oh my gosh. I nearly started crying that girl was so good! And she sang one of my favourite songs!! #BGT",'positive'),
          ("Had so much fun with @philervine today doing @belfastfoodtour - if you haven't been yet.. BOOK NOW!",'positive'),
          ("@Darth_Monty better than the beige ensemble he was rocking yesterday!",'positive'),
          ("@bredunl - ah - poor Lambs! Hope all is well!",'positive'),
          ("@TopSixNextYear a place I enjoy going. Shame about their manager tho..",'positive'),
          ("@482days  hopefully youre at invicta game tomorrow",'positive'),
          ("I need all of these #love",'positive'),
          ("The lads in the @SkySportsGolf studio are having a great laugh tonight. Super stuff. Adds to the coverage.Gr8 stuff @SarahSkySports",'positive'),
          ("for I am about to do something new Is43:19 Thank you Matt Noble @truro_baptist #pathway #see #CFeden",'positive'),
          ("@officialDB3K Yep my daughter bet on him for that very reason and won a small fortune #takethat lucky",'positive'),
          ("@strathorefarm @Farnell_Simmys Prefer to take the photos than be in then ;-)",'positive'),
          ("@Turtyforreal @hangballlouie well I'm definitely neither. First hour is a bit of a shambles so hopefully it improves.",'positive'),
          ("@Toyota I quite like the fourth-generation Prius, my favourite-generation Prius yet. ",'positive'),
          ("If tomorrow you can be in a place like this, you would be very lucky ;) #beach",'positive'),
          ("@AGRMoore we just cooked pizza -  best of both worlds buddy!",'positive'),
          ("Hearing my niece say I miss you just breaks my heart every time. She has me wrapped around her finger!",'positive'),
          ("I love this idea!",'positive'),
          ("@j7bmd smart move. Now have some wine",'positive'),
          ("@misslmassey Exactly, to be the best, you have to beat the best ! #NYR #LGR",'positive'),
          ("@rugby_ie getting up put of the sick bed to watch the rugby can't wait. should be brilliant game",'positive'),
          ("@aya_jordi @FollowsLove @Nadya130993 i need to talk niall",'positive'),
          ("I love being able to vent to my mum when I'm pissed off, she just kens it",'positive'),
          ("What a performance!  Sorry bit #teamgeorge all the way so emotional and so beautiful!  I would love to meet @BoyGeorge how lucky are u cody!",'positive'),
          ("@The45Storm Yes, just like this, with his Nan doing improvised dance...",'positive'),
          ("This is what 'exceptional leaders' do that good leaders don't",'positive'),
          ("@StuartAMPrugby @WaspsRugby @SPiutau Love it if u could join ur kid bro at",'positive'),
          ("@UlsterRugby next season. Good luck in semi #KeepsCharlesFit",'positive'),
          ("Macaroni on toast is my favourite meal but every time I eat it a think my mum does a little inside",'positive'),
          ("@therealsinead @oxbelfast sooooooo much food envy!",'positive'),
          ("I've never known anyone able to make a song so totally her own. @JanetJealousy you never cease to amaze me!",'positive'),
          ("Two year old me on my first visit to @Cambridge_Uni so proud to be studying there now.",'positive'),
          ("can we just appreciate how adorable this not so lil' bean is",'positive'),
          ("im happy i get to cuddle him tomorrow",'positive'),
          ("got bored packing, caught some of Britains Got Talent, young 12 year old just blew everyone away, what a voice absaloutly incredible range",'positive'),
          ("Tell yer wha ... I'll idly babble about the whole awful imbroglio to some random smoking strangers ... they LOVE that.",'positive'),
          ("AMAZING Golden Buzzer @AmandaHolden Beau has a God given talent !! #BGT",'positive'),
          ("Jaffa cakes are pure lovely",'positive'),
          ("All dolled up and ready for the MII ball!",'positive'),
          ("9 FUCKING DAYS TILL SLFL GLASGOW DAY 1 OMGOMG",'positive'),
          ("@LBC @beverleyturner easy on the eye bev!",'positive'),
          ("In bed early tonight as Santa Claus is coming to town... ok so it's not Santa, but Paul Heaton in DUBLIN... can't wait for the crack",'positive'),
          ("Great sunset to finish off a great day! @ Scone Palace-Crowning Place of The Kings of Scots",'positive'),
          ("Rule The World wins the Grand National with 19-year-old David Mullins our preview night Pundit.. Well done David",'positive'),
          ("@VictoriasSecret Sounds interesting, I'll be tuning in! #sbstodayfm",'positive'),
          ("Taking my casual game to a new level today.. Ditched the beanie for a baseball cap..Clearly it takes 20 years off me",'positive'),
          ("Out on the Town Tonight? Make Sure and Enjoy a Jawbox Gin &amp; Ginger.",'positive'),
          ("Kilcock V @EadestownGAA in Kilcock GAA, Tomorrow at 4pm. Support the lads!!",'positive'),
          ("@Alisazvezdica99 You too dear Alias:-) XXX",'positive'),
          ("I am soooo gonna marry this guy",'positive'),
          ("Getting ready to rock @sourcearts Thurles doors 8.30",'positive'),
          ("Thanks to Jane and all @irishskys for today!",'positive'),
          ("A fine bunch u are!!!",'positive'),
          ("@JoeManager will you tell George he's really good looking and kind cause bae.",'positive'),
          ("wow it's looking great, you're doing some job there, gonna have to get down for a look",'positive'),
          ("Was at Balmoral Show, 2011...she won her class that day and came 2nd in the ridden:-)",'positive'),
          ("can you send the video in dm please hahaha",'positive'),
          ("@Mr_NJones Safe trip :)",'positive')]
